all:
  vars:
    ansible_user: root
  children:
    proxy:
      hosts:
        proxy-lxc:
          ansible_host: 10.96.200.200
    apps:
      hosts:
        apps-lxc:
          ansible_host: 10.96.200.201
    agent:
      hosts:
        agent-lxc:
          ansible_host: 10.96.200.202
    pg:
      hosts:
        pg-lxc:
          ansible_host: 10.96.200.203
    milvus:
      hosts:
        milvus-lxc:
          ansible_host: 10.96.200.204
    files:
      hosts:
        files-lxc:
          ansible_host: 10.96.200.205
    ingest:
      hosts:
        ingest-lxc:
          ansible_host: 10.96.200.206
