all:
  vars:
    ansible_user: root
  children:
    files:
      hosts:
        files-lxc:
          ansible_host: 10.96.200.21
    pg:
      hosts:
        pg-lxc:
          ansible_host: 10.96.200.22
    milvus:
      hosts:
        milvus-lxc:
          ansible_host: 10.96.200.23
    agent:
      hosts:
        agent-lxc:
          ansible_host: 10.96.200.24
    ingest:
      hosts:
        ingest-lxc:
          ansible_host: 10.96.200.25
