"""
Milvus service for hybrid vector operations.

Handles insertion of dense, sparse (BM25), and multi-vector (ColPali) embeddings.
"""

import uuid
from typing import Dict, List, Optional

import structlog
from pymilvus import Collection, connections, utility
from rank_bm25 import BM25Okapi
from scipy.sparse import csr_matrix

logger = structlog.get_logger()


class MilvusService:
    """Service for Milvus vector database operations."""
    
    def __init__(self, config: dict):
        """Initialize Milvus service with configuration."""
        self.config = config
        self.host = config.get("milvus_host", "10.96.200.27")
        self.port = config.get("milvus_port", "19530")
        self.collection_name = config.get("milvus_collection", "documents")
        
        self.connected = False
        self.collection: Optional[Collection] = None
    
    def connect(self):
        """Connect to Milvus and load collection."""
        if self.connected:
            return
        
        try:
            connections.connect(
                "default",
                host=self.host,
                port=self.port,
            )
            
            # Check if collection exists
            if not utility.has_collection(self.collection_name):
                raise ValueError(f"Collection '{self.collection_name}' does not exist. Run hybrid_schema.py first.")
            
            # Load collection
            self.collection = Collection(self.collection_name)
            self.collection.load()
            
            self.connected = True
            logger.info(
                "Connected to Milvus",
                host=self.host,
                port=self.port,
                collection=self.collection_name,
            )
        
        except Exception as e:
            logger.error(
                "Failed to connect to Milvus",
                host=self.host,
                port=self.port,
                error=str(e),
                exc_info=True,
            )
            raise
    
    def close(self):
        """Close Milvus connections."""
        if self.connected:
            try:
                connections.disconnect("default")
                self.connected = False
                logger.info("Disconnected from Milvus")
            except Exception as e:
                logger.warning("Error disconnecting from Milvus", error=str(e))
    
    def insert_text_chunks(
        self,
        file_id: str,
        user_id: str,
        chunks: List[Dict],
        embeddings: List[List[float]],
        content_hash: str,
    ) -> int:
        """
        Insert text chunks with dense embeddings.
        
        BM25 sparse vectors are auto-generated by Milvus from the 'text' field.
        
        Args:
            file_id: File identifier
            user_id: User identifier
            chunks: List of chunk dictionaries with text, chunk_index, page_number, etc.
            embeddings: List of dense embedding vectors (1536 dims)
            content_hash: Content hash for vector reuse
        
        Returns:
            Number of vectors inserted
        """
        if not self.connected:
            self.connect()
        
        if len(chunks) != len(embeddings):
            raise ValueError(f"Chunk count ({len(chunks)}) != embedding count ({len(embeddings)})")
        
        # Generate BM25 sparse vectors
        texts = [chunk["text"] for chunk in chunks]
        tokenized_texts = [text.lower().split() for text in texts]
        bm25 = BM25Okapi(tokenized_texts)
        
        # Prepare data for insertion
        entities = []
        
        for i, (chunk, embedding) in enumerate(zip(chunks, embeddings)):
            vector_id = f"{file_id}-chunk-{chunk['chunk_index']}"
            
            # Generate BM25 sparse vector for this chunk
            bm25_scores = bm25.get_scores(tokenized_texts[i])
            # Convert to scipy sparse matrix (required by pymilvus)
            sparse_vector = csr_matrix(bm25_scores)
            
            entity = {
                "id": vector_id,
                "file_id": file_id,
                "chunk_index": chunk.get("chunk_index", i),
                "page_number": chunk.get("page_number", -1),  # -1 for non-PDF chunks
                "modality": "text",
                "text": chunk["text"],
                "text_dense": embedding,
                "text_sparse": sparse_vector,  # BM25 sparse vector
                "page_vectors": [0.0] * 128,  # Empty ColPali vector (128 dims)
                "user_id": user_id,
                "metadata": {
                    "content_hash": content_hash,
                    "char_offset": chunk.get("char_offset"),
                    "section_heading": chunk.get("section_heading"),
                    "language": chunk.get("language"),
                },
            }
            
            entities.append(entity)
        
        # Batch insert
        try:
            logger.info(
                "Inserting text chunks into Milvus",
                file_id=file_id,
                chunk_count=len(entities),
            )
            
            self.collection.insert(entities)
            self.collection.flush()
            
            logger.info(
                "Text chunks inserted successfully",
                file_id=file_id,
                vector_count=len(entities),
            )
            
            return len(entities)
        
        except Exception as e:
            logger.error(
                "Failed to insert text chunks",
                file_id=file_id,
                error=str(e),
                exc_info=True,
            )
            raise
    
    def insert_page_images(
        self,
        file_id: str,
        user_id: str,
        page_images: List[Dict],
        page_embeddings: List[List[List[float]]],
        content_hash: str,
    ) -> int:
        """
        Insert PDF page images with ColPali multi-vector embeddings.
        
        Args:
            file_id: File identifier
            user_id: User identifier
            page_images: List of page image metadata (page_number, image_path)
            page_embeddings: List of page embeddings (each page has 128 patch embeddings)
            content_hash: Content hash for vector reuse
        
        Returns:
            Number of vectors inserted
        """
        if not self.connected:
            self.connect()
        
        if not page_embeddings:
            logger.debug("No page embeddings to insert", file_id=file_id)
            return 0
        
        if len(page_images) != len(page_embeddings):
            raise ValueError(f"Page count ({len(page_images)}) != embedding count ({len(page_embeddings)})")
        
        # Prepare data for insertion
        entities = []
        
        for page_info, page_embedding in zip(page_images, page_embeddings):
            page_number = page_info.get("page_number", 1)
            vector_id = f"{file_id}-page-{page_number}"
            
            # Flatten multi-vector (128 patches × 128 dims = 16,384 dims)
            # Note: Milvus expects single vector, so we flatten
            flattened_embedding = []
            for patch in page_embedding:
                flattened_embedding.extend(patch)
            
            entity = {
                "id": vector_id,
                "file_id": file_id,
                "chunk_index": -1,  # Not a text chunk
                "page_number": page_number,
                "modality": "page_image",
                "text": f"Page {page_number}",  # Placeholder text
                "text_dense": None,
                "text_sparse": None,
                "page_vectors": flattened_embedding,
                "user_id": user_id,
                "metadata": {
                    "content_hash": content_hash,
                    "image_path": page_info.get("image_path"),
                },
            }
            
            entities.append(entity)
        
        # Batch insert
        try:
            logger.info(
                "Inserting page images into Milvus",
                file_id=file_id,
                page_count=len(entities),
            )
            
            self.collection.insert(entities)
            self.collection.flush()
            
            logger.info(
                "Page images inserted successfully",
                file_id=file_id,
                vector_count=len(entities),
            )
            
            return len(entities)
        
        except Exception as e:
            logger.error(
                "Failed to insert page images",
                file_id=file_id,
                error=str(e),
                exc_info=True,
            )
            raise
    
    def delete_file_vectors(self, file_id: str):
        """Delete all vectors for a file."""
        if not self.connected:
            self.connect()
        
        try:
            expr = f'file_id == "{file_id}"'
            self.collection.delete(expr)
            self.collection.flush()
            
            logger.info("Deleted vectors for file", file_id=file_id)
        
        except Exception as e:
            logger.error(
                "Failed to delete vectors",
                file_id=file_id,
                error=str(e),
                exc_info=True,
            )
            raise
