"""
Environment Variable Generator

Generates environment variables for deployed apps based on:
- Manifest requirements
- Known service endpoints
- Database credentials
- Container configuration
"""

import logging
from typing import Dict, Optional
from .models import BusiboxManifest, DeploymentConfig
from .config import config

logger = logging.getLogger(__name__)


def is_docker_environment() -> bool:
    """Check if running in Docker (local development)"""
    return not config.postgres_host.startswith('10.')


def get_service_endpoints(environment: str = 'production') -> Dict[str, str]:
    """
    Get service endpoint URLs based on environment.
    
    In Docker: Use container hostnames
    In Proxmox: Use container IPs
    """
    if is_docker_environment():
        return {
            # Database
            'POSTGRES_HOST': 'postgres',
            'POSTGRES_PORT': '5432',
            
            # Auth
            'AUTHZ_BASE_URL': 'http://authz-api:8010',
            
            # LLM
            'LITELLM_BASE_URL': 'http://litellm:4000/v1',
            
            # APIs
            'AGENT_API_URL': 'http://agent-api:8000',
            'INGEST_API_URL': 'http://ingest-api:8002',
            'SEARCH_API_URL': 'http://search-api:8003',
            
            # Storage
            'MINIO_ENDPOINT': 'minio:9000',
            'REDIS_HOST': 'redis',
            'REDIS_PORT': '6379',
        }
    else:
        # Proxmox LXC environment - use IPs from config
        # These would typically be set via Ansible vars
        base = '10.96.200' if environment == 'production' else '10.96.201'
        return {
            # Database
            'POSTGRES_HOST': f'{base}.203',
            'POSTGRES_PORT': '5432',
            
            # Auth
            'AUTHZ_BASE_URL': f'http://{base}.210:8010',
            
            # LLM
            'LITELLM_BASE_URL': f'http://{base}.207:4000/v1',
            
            # APIs
            'AGENT_API_URL': f'http://{base}.202:8000',
            'INGEST_API_URL': f'http://{base}.206:8002',
            'SEARCH_API_URL': f'http://{base}.204:8003',
            
            # Storage
            'MINIO_ENDPOINT': f'{base}.205:9000',
            'REDIS_HOST': f'{base}.206',
            'REDIS_PORT': '6379',
        }


def generate_env_vars(
    manifest: BusiboxManifest,
    deploy_config: DeploymentConfig,
    database_url: Optional[str] = None
) -> Dict[str, str]:
    """
    Generate environment variables for an app deployment.
    
    Args:
        manifest: App manifest from busibox.json
        deploy_config: Deployment configuration
        database_url: Provisioned database URL (if applicable)
    
    Returns:
        Dictionary of environment variables
    """
    env = {}
    
    # Base environment
    env['NODE_ENV'] = 'production' if deploy_config.environment == 'production' else 'development'
    env['PORT'] = str(manifest.defaultPort)
    
    # Database URL (if provisioned)
    if database_url:
        env['DATABASE_URL'] = database_url
    
    # Get service endpoints
    endpoints = get_service_endpoints(deploy_config.environment)
    
    # Add required env vars from manifest
    for var in manifest.requiredEnvVars:
        # Check if it's a known service endpoint
        if var in endpoints:
            env[var] = endpoints[var]
        elif var in deploy_config.secrets:
            env[var] = deploy_config.secrets[var]
        else:
            logger.warning(f"Required env var {var} not provided")
    
    # Add optional env vars if available
    for var in manifest.optionalEnvVars:
        if var in endpoints:
            env[var] = endpoints[var]
        elif var in deploy_config.secrets:
            env[var] = deploy_config.secrets[var]
    
    # Always include common Busibox service endpoints for apps that use them
    common_vars = [
        'AUTHZ_BASE_URL',
        'LITELLM_BASE_URL',
        'AGENT_API_URL',
        'INGEST_API_URL',
        'SEARCH_API_URL',
    ]
    
    for var in common_vars:
        if var not in env and var in endpoints:
            env[var] = endpoints[var]
    
    # Add any additional secrets from deployment config
    for key, value in deploy_config.secrets.items():
        if key not in env:
            env[key] = value
    
    logger.info(f"Generated {len(env)} environment variables for {manifest.name}")
    return env


def generate_env_file_content(env_vars: Dict[str, str]) -> str:
    """
    Generate .env file content from environment variables.
    
    Args:
        env_vars: Dictionary of environment variables
    
    Returns:
        String content for .env file
    """
    lines = [
        "# Auto-generated by Busibox Deploy Service",
        "# Do not edit manually - changes will be overwritten on next deploy",
        ""
    ]
    
    for key, value in sorted(env_vars.items()):
        # Escape values that contain special characters
        if any(c in value for c in [' ', '"', "'", '$', '\n']):
            # Use double quotes and escape
            value = value.replace('\\', '\\\\').replace('"', '\\"')
            lines.append(f'{key}="{value}"')
        else:
            lines.append(f'{key}={value}')
    
    return '\n'.join(lines) + '\n'
