"""
Nginx Configuration

Automatically configures nginx routes for deployed apps via SSH.
In Docker/local environments, skips actual configuration.
"""

import asyncio
import logging
import os
import shlex
from typing import Optional, Tuple
from .models import BusiboxManifest
from .config import config
from .database import execute_ssh_command

logger = logging.getLogger(__name__)

# Container prefix for Docker container names
CONTAINER_PREFIX = os.environ.get("CONTAINER_PREFIX", "dev")

# In modern Busibox Docker deployments, nginx is bundled inside the core-apps container.
# The standalone nginx container only exists in "hybrid" profile.
#
# Allow override in case an installation runs nginx elsewhere.
NGINX_CONTAINER_OVERRIDE = os.environ.get("BUSIBOX_NGINX_CONTAINER", "").strip()
DEFAULT_NGINX_CONTAINERS = [
    f"{CONTAINER_PREFIX}-core-apps",  # nginx inside core-apps (default)
    f"{CONTAINER_PREFIX}-nginx",      # standalone nginx (hybrid profile)
]


def is_docker_environment() -> bool:
    """Check if running in Docker (local development)"""
    # In Docker, POSTGRES_HOST is typically 'postgres' (container name) not an IP
    return not config.postgres_host.startswith('10.')


class NginxConfigurator:
    def __init__(self):
        self.nginx_host = config.nginx_host
        self.config_dir = config.nginx_config_dir
        self.enabled_dir = config.nginx_enabled_dir
        self.apps_container_ip = config.apps_container_ip
    
    def generate_location_config(
        self,
        manifest: BusiboxManifest,
        container_ip: str
    ) -> str:
        """Generate nginx location block for app
        
        Args:
            manifest: App manifest
            container_ip: Either an IP address (10.x.x.x) or Docker service name (user-apps)
        
        Note: Uses nginx variable for proxy_pass to enable dynamic DNS resolution.
        This allows nginx to start even if the backend service isn't running yet,
        and resolves the hostname at request time rather than at startup.
        """
        
        # Remove trailing slash from path
        path = manifest.defaultPath.rstrip('/')
        
        # For Docker service names, include the port in the proxy_pass
        # For IPs, it's already formatted
        if ':' in container_ip:
            # Already has port (Docker service:port format)
            backend = container_ip
        else:
            # IP address - add port
            backend = f"{container_ip}:{manifest.defaultPort}"
        
        # Create a variable name from the app ID (replace dashes with underscores)
        var_name = manifest.id.replace('-', '_')
        
        config_content = f"""
# {manifest.name} - Auto-generated by deployment service
# App ID: {manifest.id}
# Uses dynamic DNS resolution via variable to allow nginx to start
# even if this app's backend service isn't running yet.
#
# Next.js apps run with basePath={path}, so we preserve the path prefix.
# This matches the agent-manager nginx config pattern exactly.
# proxy_pass WITHOUT trailing slash = preserve the request URI

location ^~ {path} {{
    set $backend_{var_name} http://{backend};
    proxy_pass $backend_{var_name};
    proxy_http_version 1.1;

    # Debug/provenance headers (helps confirm nginx is matching this location)
    add_header X-Busibox-App "{manifest.id}" always;
    
    # Headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Prefix {path};
    
    # WebSocket support for Next.js HMR
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    
    # Timeouts - extended for WebSocket/HMR
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 86400;
    
    # Buffering
    proxy_buffering off;
    proxy_request_buffering off;
}}
"""
        return config_content
    
    async def write_config(
        self,
        manifest: BusiboxManifest,
        container_ip: str
    ) -> Tuple[bool, str]:
        """Write nginx configuration file via SSH"""
        
        config_content = self.generate_location_config(manifest, container_ip)
        config_path = f"{self.config_dir}/{manifest.id}.conf"
        
        # Escape for shell
        escaped_content = config_content.replace("'", "'\\''")
        
        # Create directory if needed and write file
        command = f"""
mkdir -p {self.config_dir}
cat > {config_path} << 'NGINX_EOF'
{config_content}
NGINX_EOF
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to write nginx config: {stderr}")
            return False, f"Failed to write config: {stderr}"
        
        logger.info(f"Nginx config written: {config_path}")
        return True, config_path
    
    async def enable_config(self, manifest: BusiboxManifest) -> Tuple[bool, str]:
        """Enable nginx configuration (create symlink) via SSH"""
        
        source = f"{self.config_dir}/{manifest.id}.conf"
        target = f"{self.enabled_dir}/{manifest.id}.conf"
        
        command = f"""
rm -f {target}
ln -s {source} {target}
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to enable nginx config: {stderr}")
            return False, f"Failed to enable config: {stderr}"
        
        logger.info(f"Nginx config enabled: {target}")
        return True, target
    
    async def validate_config(self) -> Tuple[bool, str]:
        """Validate nginx configuration via SSH"""
        
        command = "nginx -t 2>&1"
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        output = stdout + stderr
        
        if code == 0:
            logger.info("Nginx config validation passed")
            return True, output
        else:
            logger.error(f"Nginx config validation failed: {output}")
            return False, output
    
    async def reload_nginx(self) -> Tuple[bool, str]:
        """Reload nginx configuration via SSH"""
        
        command = "systemctl reload nginx"
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code == 0:
            logger.info("Nginx reloaded successfully")
            return True, "Nginx reloaded"
        else:
            error = stderr or stdout
            logger.error(f"Failed to reload nginx: {error}")
            return False, f"Failed to reload: {error}"
    
    async def configure_app(
        self,
        manifest: BusiboxManifest,
        container_ip: Optional[str] = None
    ) -> Tuple[bool, str]:
        """Configure nginx for app (write, validate, enable, reload)"""
        
        # In Docker/local environment, write config directly to mounted volume
        if is_docker_environment():
            logger.info("Docker environment - writing config to mounted volume")
            
            # For Docker, use the user-apps container as the backend
            # Container name resolution via Docker DNS
            backend = f"user-apps:{manifest.defaultPort}"
            
            # Generate config
            config_content = self.generate_location_config(manifest, backend)
            
            # Write to mounted directory (accessible from deploy-api container)
            # The busibox directory is mounted at BUSIBOX_HOST_PATH inside deploy-api
            # and nginx mounts ./config/nginx-sites/apps to /etc/nginx/conf.d/apps
            busibox_path = os.environ.get("BUSIBOX_HOST_PATH", "/busibox")
            config_path = f"{busibox_path}/config/nginx-sites/apps/{manifest.id}.conf"
            
            try:
                os.makedirs(os.path.dirname(config_path), exist_ok=True)
                
                with open(config_path, 'w') as f:
                    f.write(config_content)
                
                logger.info(f"Wrote nginx config to {config_path}")
                
                # Reload nginx via docker exec.
                # nginx lives inside core-apps in standard Busibox Docker mode.
                import subprocess

                containers_to_try = (
                    [NGINX_CONTAINER_OVERRIDE]
                    if NGINX_CONTAINER_OVERRIDE
                    else list(DEFAULT_NGINX_CONTAINERS)
                )

                last_error = ""
                for container in containers_to_try:
                    # Ensure the config is present inside the nginx container.
                    # In some environments, the host bind-mount path can differ from
                    # what core-apps/nginx is mounting, so writing to the host path
                    # alone is not sufficient.
                    target_path = f"/etc/nginx/conf.d/apps/{manifest.id}.conf"
                    exists_result = subprocess.run(
                        ['docker', 'exec', container, 'sh', '-c', f'test -f {shlex.quote(target_path)}'],
                        capture_output=True,
                        text=True,
                    )
                    if exists_result.returncode != 0:
                        # Write config into the container directly.
                        heredoc_cmd = (
                            f"cat > {shlex.quote(target_path)} << 'NGINX_EOF'\n"
                            f"{config_content}\n"
                            f"NGINX_EOF\n"
                        )
                        write_result = subprocess.run(
                            ['docker', 'exec', container, 'sh', '-c', heredoc_cmd],
                            capture_output=True,
                            text=True,
                        )
                        if write_result.returncode != 0:
                            last_error = (write_result.stderr or write_result.stdout or "").strip()
                            logger.warning(f"Failed to write app config into {container}: {last_error}")
                            continue

                    # First validate config so reload errors are actionable
                    test_result = subprocess.run(
                        ['docker', 'exec', container, 'nginx', '-t'],
                        capture_output=True,
                        text=True
                    )
                    if test_result.returncode != 0:
                        last_error = (test_result.stderr or test_result.stdout or "").strip()
                        logger.warning(f"Nginx config test failed in {container}: {last_error}")
                        continue

                    reload_result = subprocess.run(
                        ['docker', 'exec', container, 'nginx', '-s', 'reload'],
                        capture_output=True,
                        text=True
                    )

                    if reload_result.returncode == 0:
                        logger.info(f"Nginx reloaded successfully in {container}")
                        return True, f"App configured at {manifest.defaultPath}"

                    last_error = (reload_result.stderr or reload_result.stdout or "").strip()
                    logger.warning(f"Nginx reload failed in {container}: {last_error}")

                return False, f"Config written but reload failed: {last_error or 'unknown error'}"
                    
            except Exception as e:
                logger.error(f"Failed to write nginx config: {e}")
                return False, f"Failed to write nginx config: {e}"
        
        # LXC/Proxmox environment - use SSH
        if not container_ip:
            container_ip = self.apps_container_ip
        
        # Write configuration
        success, msg = await self.write_config(manifest, container_ip)
        if not success:
            return False, f"Failed to write nginx configuration: {msg}"
        
        # Validate configuration
        valid, output = await self.validate_config()
        if not valid:
            return False, f"Nginx configuration validation failed: {output}"
        
        # Enable configuration
        success, msg = await self.enable_config(manifest)
        if not success:
            return False, f"Failed to enable nginx configuration: {msg}"
        
        # Reload nginx
        success, msg = await self.reload_nginx()
        if not success:
            return False, f"Failed to reload nginx: {msg}"
        
        return True, f"Nginx configured for {manifest.name} at {manifest.defaultPath}"
    
    async def remove_config(self, manifest: BusiboxManifest) -> Tuple[bool, str]:
        """Remove nginx configuration for app via SSH"""
        
        target = f"{self.enabled_dir}/{manifest.id}.conf"
        source = f"{self.config_dir}/{manifest.id}.conf"
        
        command = f"""
rm -f {target}
rm -f {source}
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to remove nginx config: {stderr}")
            return False, f"Failed to remove: {stderr}"
        
        # Reload nginx
        await self.reload_nginx()
        
        logger.info(f"Nginx config removed for {manifest.id}")
        return True, f"Removed config for {manifest.id}"
