"""
Nginx Configuration

Automatically configures nginx routes for deployed apps via SSH.
In Docker/local environments, skips actual configuration.
"""

import asyncio
import logging
import os
import shlex
import subprocess
from typing import List, Optional, Tuple
from .models import BusiboxManifest, ServiceEndpoint
from .config import config
from .database import execute_ssh_command
from .core_app_executor import is_docker_environment

logger = logging.getLogger(__name__)

# Container prefix for Docker container names.
# This is required so deploy-api always targets the canonical proxy container.
CONTAINER_PREFIX = os.environ.get("CONTAINER_PREFIX", "").strip()
if not CONTAINER_PREFIX:
    raise RuntimeError("CONTAINER_PREFIX must be set for deploy-api")

PROXY_CONTAINER = f"{CONTAINER_PREFIX}-proxy"
CORE_APP_PATHS = {"/portal", "/agents", "/builder"}


class NginxConfigurator:
    def __init__(self):
        self.nginx_host = config.nginx_host
        self.config_dir = config.nginx_config_dir
        self.enabled_dir = config.nginx_enabled_dir
        self.apps_container_ip = config.apps_container_ip

    @staticmethod
    def _is_core_app_route(manifest: BusiboxManifest) -> bool:
        return manifest.defaultPath.rstrip('/') in CORE_APP_PATHS
    
    def generate_location_config(
        self,
        manifest: BusiboxManifest,
        container_ip: str,
        port_override: Optional[int] = None,
    ) -> str:
        """Generate nginx location block for app
        
        Args:
            manifest: App manifest
            container_ip: Either an IP address (10.x.x.x) or Docker service name (user-apps)
            port_override: If set, use this port instead of manifest.defaultPort
        
        Note: Uses nginx variable for proxy_pass to enable dynamic DNS resolution.
        This allows nginx to start even if the backend service isn't running yet,
        and resolves the hostname at request time rather than at startup.
        """
        
        # Remove trailing slash from path
        path = manifest.defaultPath.rstrip('/')
        
        effective_port = port_override if port_override is not None else manifest.defaultPort
        
        # For Docker service names, include the port in the proxy_pass
        # For IPs, it's already formatted
        if ':' in container_ip:
            # Already has port (Docker service:port format)
            backend = container_ip
        else:
            # IP address - add port
            backend = f"{container_ip}:{effective_port}"
        
        # Create a variable name from the app ID (replace dashes with underscores)
        var_name = manifest.id.replace('-', '_')
        
        config_content = f"""
# {manifest.name} - Auto-generated by deployment service
# App ID: {manifest.id}
# Uses dynamic DNS resolution via variable to allow nginx to start
# even if this app's backend service isn't running yet.
#
# Next.js apps run with basePath={path}, so we preserve the path prefix.
# This matches the busibox-agents nginx config pattern exactly.
# proxy_pass WITHOUT trailing slash = preserve the request URI

location ^~ {path} {{
    set $backend_{var_name} http://{backend};
    proxy_pass $backend_{var_name};
    proxy_http_version 1.1;

    # Debug/provenance headers (helps confirm nginx is matching this location)
    add_header X-Busibox-App "{manifest.id}" always;
    
    # Headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Prefix {path};
    
    # WebSocket support for Next.js HMR
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    
    # Timeouts - extended for WebSocket/HMR
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 86400;
    
    # Buffering
    proxy_buffering off;
    proxy_request_buffering off;
}}
"""
        return config_content
    
    def generate_custom_location_configs(
        self,
        manifest: BusiboxManifest,
        backend_prefix: str,
    ) -> str:
        """Generate nginx location blocks for a custom multi-service app.

        Args:
            manifest: App manifest with services[] endpoints.
            backend_prefix: For Docker this is the compose project name (used
                as container hostname via Docker DNS). For LXC it is the
                container IP address.

        Returns:
            Complete nginx config file content with one location per service.
        """
        if not manifest.services:
            return ""

        header = (
            f"# {manifest.name} - Custom service auto-generated by deployment service\n"
            f"# App ID: {manifest.id}\n"
            f"# Services: {', '.join(s.name for s in manifest.services)}\n\n"
        )

        blocks: List[str] = []
        for svc in manifest.services:
            var_name = f"{manifest.id}_{svc.name}".replace("-", "_")
            backend = f"{backend_prefix}-{svc.name}:{svc.port}"
            path = svc.path.rstrip("/")

            if svc.stripPath:
                # Rewrite strips the service path prefix before forwarding
                block = f"""location ^~ {path}/ {{
    set $backend_{var_name} http://{backend};
    rewrite ^{path}(/.*)?$ $1 break;
    proxy_pass $backend_{var_name};
    proxy_http_version 1.1;

    add_header X-Busibox-App "{manifest.id}" always;
    add_header X-Busibox-Service "{svc.name}" always;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Prefix {path};

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 86400;

    proxy_buffering off;
    proxy_request_buffering off;
}}"""
            else:
                # Pass through the full path as-is
                block = f"""location ^~ {path}/ {{
    set $backend_{var_name} http://{backend};
    proxy_pass $backend_{var_name};
    proxy_http_version 1.1;

    add_header X-Busibox-App "{manifest.id}" always;
    add_header X-Busibox-Service "{svc.name}" always;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Prefix {path};

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 86400;

    proxy_buffering off;
    proxy_request_buffering off;
}}"""
            blocks.append(block)

        return header + "\n\n".join(blocks) + "\n"

    async def write_config(
        self,
        manifest: BusiboxManifest,
        container_ip: str,
        port_override: Optional[int] = None,
    ) -> Tuple[bool, str]:
        """Write nginx configuration file via SSH"""
        
        config_content = self.generate_location_config(manifest, container_ip, port_override=port_override)
        config_path = f"{self.config_dir}/{manifest.id}.conf"
        
        # Escape for shell
        escaped_content = config_content.replace("'", "'\\''")
        
        # Create directory if needed and write file
        command = f"""
mkdir -p {self.config_dir}
cat > {config_path} << 'NGINX_EOF'
{config_content}
NGINX_EOF
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to write nginx config: {stderr}")
            return False, f"Failed to write config: {stderr}"
        
        logger.info(f"Nginx config written: {config_path}")
        return True, config_path
    
    async def enable_config(self, manifest: BusiboxManifest) -> Tuple[bool, str]:
        """Enable nginx configuration (create symlink) via SSH"""
        
        source = f"{self.config_dir}/{manifest.id}.conf"
        target = f"{self.enabled_dir}/{manifest.id}.conf"
        
        command = f"""
rm -f {target}
ln -s {source} {target}
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to enable nginx config: {stderr}")
            return False, f"Failed to enable config: {stderr}"
        
        logger.info(f"Nginx config enabled: {target}")
        return True, target
    
    async def validate_config(self) -> Tuple[bool, str]:
        """Validate nginx configuration via SSH"""
        
        command = "nginx -t 2>&1"
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        output = stdout + stderr
        
        if code == 0:
            logger.info("Nginx config validation passed")
            return True, output
        else:
            logger.error(f"Nginx config validation failed: {output}")
            return False, output
    
    async def reload_nginx(self) -> Tuple[bool, str]:
        """Reload nginx configuration via SSH"""
        
        command = "systemctl reload nginx"
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code == 0:
            logger.info("Nginx reloaded successfully")
            return True, "Nginx reloaded"
        else:
            error = stderr or stdout
            logger.error(f"Failed to reload nginx: {error}")
            return False, f"Failed to reload: {error}"
    
    async def configure_custom_app(
        self,
        manifest: BusiboxManifest,
        project_name: str,
        container_ip: Optional[str] = None,
    ) -> Tuple[bool, str]:
        """Configure nginx for a custom multi-service app.

        Args:
            manifest: App manifest with services[] endpoints.
            project_name: Docker Compose project name (used as DNS prefix in Docker).
            container_ip: Container IP for LXC/Proxmox backend.
        """
        if not manifest.services:
            return False, "No services defined in manifest"

        backend_prefix = project_name if is_docker_environment() else (container_ip or "127.0.0.1")
        config_content = self.generate_custom_location_configs(manifest, backend_prefix)

        if is_docker_environment():
            busibox_path = os.environ.get("BUSIBOX_HOST_PATH", "/busibox")
            config_path = f"{busibox_path}/config/nginx-sites/apps/{manifest.id}.conf"
            try:
                os.makedirs(os.path.dirname(config_path), exist_ok=True)
                with open(config_path, "w") as f:
                    f.write(config_content)
                logger.info("Wrote custom nginx config to %s", config_path)

                target_path = f"/etc/nginx/conf.d/apps/{manifest.id}.conf"
                heredoc_cmd = (
                    f"cat > {shlex.quote(target_path)} << 'NGINX_EOF'\n"
                    f"{config_content}\n"
                    f"NGINX_EOF\n"
                )
                write_result = subprocess.run(
                    ["docker", "exec", PROXY_CONTAINER, "sh", "-c", heredoc_cmd],
                    capture_output=True, text=True,
                )
                if write_result.returncode != 0:
                    error = (write_result.stderr or write_result.stdout or "").strip()
                    return False, f"Failed to write config into {PROXY_CONTAINER}: {error}"

                test_result = subprocess.run(
                    ["docker", "exec", PROXY_CONTAINER, "nginx", "-t"],
                    capture_output=True, text=True,
                )
                if test_result.returncode != 0:
                    error = (test_result.stderr or test_result.stdout or "").strip()
                    return False, f"Nginx config test failed: {error}"

                reload_result = subprocess.run(
                    ["docker", "exec", PROXY_CONTAINER, "nginx", "-s", "reload"],
                    capture_output=True, text=True,
                )
                if reload_result.returncode != 0:
                    error = (reload_result.stderr or reload_result.stdout or "").strip()
                    return False, f"Nginx reload failed: {error}"

                logger.info("Nginx reloaded for custom service %s", manifest.id)
                svc_paths = ", ".join(s.path for s in manifest.services)
                return True, f"Custom service configured at paths: {svc_paths}"
            except Exception as e:
                logger.error("Failed to write custom nginx config: %s", e)
                return False, f"Failed to write custom nginx config: {e}"

        # LXC/Proxmox backend -- write via SSH
        config_path = f"{self.config_dir}/{manifest.id}.conf"
        command = f"""
mkdir -p {self.config_dir}
cat > {config_path} << 'NGINX_EOF'
{config_content}
NGINX_EOF
"""
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        if code != 0:
            return False, f"Failed to write custom nginx config: {stderr}"

        valid, output = await self.validate_config()
        if not valid:
            await self._remove_config_file(manifest)
            return False, f"Nginx validation failed: {output}"

        success, msg = await self.reload_nginx()
        if not success:
            return False, f"Failed to reload nginx: {msg}"

        svc_paths = ", ".join(s.path for s in manifest.services)
        return True, f"Custom service configured at paths: {svc_paths}"

    async def configure_app(
        self,
        manifest: BusiboxManifest,
        container_ip: Optional[str] = None,
        port_override: Optional[int] = None,
    ) -> Tuple[bool, str]:
        """Configure nginx for app (write, validate, enable, reload)"""
        if self._is_core_app_route(manifest):
            # Core app routes are defined in base nginx configs
            # (e.g. /portal, /agents, /builder). Do not create dynamic snippets.
            logger.info(
                "Skipping dynamic nginx config for core app route %s (%s)",
                manifest.defaultPath,
                manifest.id,
            )
            await self.remove_config(manifest)
            return True, f"Core app route {manifest.defaultPath} uses base nginx config"
        
        # Custom services have their own multi-endpoint config method
        if manifest.appMode == "custom" and manifest.services:
            from .custom_service_executor import _project_name
            return await self.configure_custom_app(
                manifest,
                project_name=_project_name(manifest.id),
                container_ip=container_ip,
            )

        # In Docker/local environment, write config directly to mounted volume
        if is_docker_environment():
            logger.info("Docker environment - writing config to mounted volume")
            
            # For Docker, use the user-apps container as the backend
            # Container name resolution via Docker DNS
            effective_port = port_override if port_override is not None else manifest.defaultPort
            backend = f"user-apps:{effective_port}"
            
            # Generate config
            config_content = self.generate_location_config(manifest, backend, port_override=port_override)
            
            # Write to mounted directory (accessible from deploy-api container)
            # The busibox directory is mounted at BUSIBOX_HOST_PATH inside deploy-api
            # and nginx mounts ./config/nginx-sites/apps to /etc/nginx/conf.d/apps
            busibox_path = os.environ.get("BUSIBOX_HOST_PATH", "/busibox")
            config_path = f"{busibox_path}/config/nginx-sites/apps/{manifest.id}.conf"
            
            try:
                os.makedirs(os.path.dirname(config_path), exist_ok=True)
                
                with open(config_path, 'w') as f:
                    f.write(config_content)
                
                logger.info(f"Wrote nginx config to {config_path}")
                
                # Reload nginx via docker exec on canonical proxy container.
                target_path = f"/etc/nginx/conf.d/apps/{manifest.id}.conf"
                exists_result = subprocess.run(
                    ['docker', 'exec', PROXY_CONTAINER, 'sh', '-c', f'test -f {shlex.quote(target_path)}'],
                    capture_output=True,
                    text=True,
                )
                if exists_result.returncode != 0:
                    heredoc_cmd = (
                        f"cat > {shlex.quote(target_path)} << 'NGINX_EOF'\n"
                        f"{config_content}\n"
                        f"NGINX_EOF\n"
                    )
                    write_result = subprocess.run(
                        ['docker', 'exec', PROXY_CONTAINER, 'sh', '-c', heredoc_cmd],
                        capture_output=True,
                        text=True,
                    )
                    if write_result.returncode != 0:
                        error = (write_result.stderr or write_result.stdout or "").strip()
                        return False, f"Failed to write app config into {PROXY_CONTAINER}: {error}"

                test_result = subprocess.run(
                    ['docker', 'exec', PROXY_CONTAINER, 'nginx', '-t'],
                    capture_output=True,
                    text=True
                )
                if test_result.returncode != 0:
                    error = (test_result.stderr or test_result.stdout or "").strip()
                    return False, f"Nginx config test failed in {PROXY_CONTAINER}: {error}"

                reload_result = subprocess.run(
                    ['docker', 'exec', PROXY_CONTAINER, 'nginx', '-s', 'reload'],
                    capture_output=True,
                    text=True
                )
                if reload_result.returncode != 0:
                    error = (reload_result.stderr or reload_result.stdout or "").strip()
                    return False, f"Nginx reload failed in {PROXY_CONTAINER}: {error}"

                logger.info(f"Nginx reloaded successfully in {PROXY_CONTAINER}")
                return True, f"App configured at {manifest.defaultPath}"
                    
            except Exception as e:
                logger.error(f"Failed to write nginx config: {e}")
                return False, f"Failed to write nginx config: {e}"
        
        # LXC/Proxmox environment - use SSH
        if not container_ip:
            container_ip = self.apps_container_ip
        
        # Write configuration (location snippet to app-locations/ directory)
        success, msg = await self.write_config(manifest, container_ip, port_override=port_override)
        if not success:
            return False, f"Failed to write nginx configuration: {msg}"
        
        # Validate configuration
        # The location snippets in app-locations/ are included inside the server
        # block via "include /etc/nginx/app-locations/*.conf;" in the vhost config.
        # No symlink into sites-enabled is needed.
        valid, output = await self.validate_config()
        if not valid:
            # Validation failed - remove the bad config to avoid breaking nginx
            await self._remove_config_file(manifest)
            return False, f"Nginx configuration validation failed: {output}"
        
        # Reload nginx
        success, msg = await self.reload_nginx()
        if not success:
            return False, f"Failed to reload nginx: {msg}"
        
        return True, f"Nginx configured for {manifest.name} at {manifest.defaultPath}"
    
    async def _remove_config_file(self, manifest: BusiboxManifest) -> Tuple[bool, str]:
        """Remove just the config file (used for cleanup on validation failure)"""
        config_path = f"{self.config_dir}/{manifest.id}.conf"
        command = f"rm -f {config_path}"
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        if code != 0:
            return False, f"Failed to remove config file: {stderr}"
        return True, f"Removed {config_path}"

    async def remove_config(self, manifest: BusiboxManifest) -> Tuple[bool, str]:
        """Remove nginx configuration for app via SSH"""
        if is_docker_environment():
            busibox_path = os.environ.get("BUSIBOX_HOST_PATH", "/busibox")
            host_config = f"{busibox_path}/config/nginx-sites/apps/{manifest.id}.conf"
            container_config = f"/etc/nginx/conf.d/apps/{manifest.id}.conf"

            try:
                if os.path.exists(host_config):
                    os.remove(host_config)

                subprocess.run(
                    ['docker', 'exec', PROXY_CONTAINER, 'sh', '-c', f'rm -f {shlex.quote(container_config)}'],
                    capture_output=True,
                    text=True,
                )

                test_result = subprocess.run(
                    ['docker', 'exec', PROXY_CONTAINER, 'nginx', '-t'],
                    capture_output=True,
                    text=True,
                )
                if test_result.returncode != 0:
                    error = (test_result.stderr or test_result.stdout or "").strip()
                    return False, f"Nginx config test failed in {PROXY_CONTAINER}: {error}"

                reload_result = subprocess.run(
                    ['docker', 'exec', PROXY_CONTAINER, 'nginx', '-s', 'reload'],
                    capture_output=True,
                    text=True,
                )
                if reload_result.returncode != 0:
                    error = (reload_result.stderr or reload_result.stdout or "").strip()
                    return False, f"Nginx reload failed in {PROXY_CONTAINER}: {error}"

                logger.info("Removed docker app config for %s", manifest.id)
                return True, f"Removed config for {manifest.id}"
            except Exception as e:
                logger.error("Failed to remove docker nginx config: %s", e)
                return False, f"Failed to remove config: {e}"

        # Remove from app-locations dir (current approach)
        config_path = f"{self.config_dir}/{manifest.id}.conf"
        # Also clean up any legacy symlink in sites-enabled (from older deploys)
        legacy_enabled = f"{self.enabled_dir}/{manifest.id}.conf"
        # Also clean up legacy sites-available/apps/ path
        legacy_available = f"/etc/nginx/sites-available/apps/{manifest.id}.conf"
        
        command = f"""
rm -f {config_path}
rm -f {legacy_enabled}
rm -f {legacy_available}
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to remove nginx config: {stderr}")
            return False, f"Failed to remove: {stderr}"
        
        # Reload nginx
        await self.reload_nginx()
        
        logger.info(f"Nginx config removed for {manifest.id}")
        return True, f"Removed config for {manifest.id}"
