"""
Nginx Configuration

Automatically configures nginx routes for deployed apps via SSH.
"""

import asyncio
import logging
from typing import Optional, Tuple
from .models import BusiboxManifest
from .config import config
from .database import execute_ssh_command

logger = logging.getLogger(__name__)


class NginxConfigurator:
    def __init__(self):
        self.nginx_host = config.nginx_host
        self.config_dir = config.nginx_config_dir
        self.enabled_dir = config.nginx_enabled_dir
        self.apps_container_ip = config.apps_container_ip
    
    def generate_location_config(
        self,
        manifest: BusiboxManifest,
        container_ip: str
    ) -> str:
        """Generate nginx location block for app"""
        
        # Remove trailing slash from path
        path = manifest.defaultPath.rstrip('/')
        
        config_content = f"""
# {manifest.name} - Auto-generated by deployment service
# App ID: {manifest.id}
# Generated at: $(date)

location {path}/ {{
    proxy_pass http://{container_ip}:{manifest.defaultPort}/;
    proxy_http_version 1.1;
    
    # Headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    
    # WebSocket support
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    
    # Timeouts
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    
    # Buffering
    proxy_buffering off;
    proxy_request_buffering off;
}}

# Health check endpoint
location {path}{manifest.healthEndpoint} {{
    proxy_pass http://{container_ip}:{manifest.defaultPort}{manifest.healthEndpoint};
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    access_log off;
}}
"""
        return config_content
    
    async def write_config(
        self,
        manifest: BusiboxManifest,
        container_ip: str
    ) -> Tuple[bool, str]:
        """Write nginx configuration file via SSH"""
        
        config_content = self.generate_location_config(manifest, container_ip)
        config_path = f"{self.config_dir}/{manifest.id}.conf"
        
        # Escape for shell
        escaped_content = config_content.replace("'", "'\\''")
        
        # Create directory if needed and write file
        command = f"""
mkdir -p {self.config_dir}
cat > {config_path} << 'NGINX_EOF'
{config_content}
NGINX_EOF
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to write nginx config: {stderr}")
            return False, f"Failed to write config: {stderr}"
        
        logger.info(f"Nginx config written: {config_path}")
        return True, config_path
    
    async def enable_config(self, manifest: BusiboxManifest) -> Tuple[bool, str]:
        """Enable nginx configuration (create symlink) via SSH"""
        
        source = f"{self.config_dir}/{manifest.id}.conf"
        target = f"{self.enabled_dir}/{manifest.id}.conf"
        
        command = f"""
rm -f {target}
ln -s {source} {target}
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to enable nginx config: {stderr}")
            return False, f"Failed to enable config: {stderr}"
        
        logger.info(f"Nginx config enabled: {target}")
        return True, target
    
    async def validate_config(self) -> Tuple[bool, str]:
        """Validate nginx configuration via SSH"""
        
        command = "nginx -t 2>&1"
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        output = stdout + stderr
        
        if code == 0:
            logger.info("Nginx config validation passed")
            return True, output
        else:
            logger.error(f"Nginx config validation failed: {output}")
            return False, output
    
    async def reload_nginx(self) -> Tuple[bool, str]:
        """Reload nginx configuration via SSH"""
        
        command = "systemctl reload nginx"
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code == 0:
            logger.info("Nginx reloaded successfully")
            return True, "Nginx reloaded"
        else:
            error = stderr or stdout
            logger.error(f"Failed to reload nginx: {error}")
            return False, f"Failed to reload: {error}"
    
    async def configure_app(
        self,
        manifest: BusiboxManifest,
        container_ip: Optional[str] = None
    ) -> Tuple[bool, str]:
        """Configure nginx for app (write, validate, enable, reload)"""
        
        if not container_ip:
            container_ip = self.apps_container_ip
        
        # Write configuration
        success, msg = await self.write_config(manifest, container_ip)
        if not success:
            return False, f"Failed to write nginx configuration: {msg}"
        
        # Validate configuration
        valid, output = await self.validate_config()
        if not valid:
            return False, f"Nginx configuration validation failed: {output}"
        
        # Enable configuration
        success, msg = await self.enable_config(manifest)
        if not success:
            return False, f"Failed to enable nginx configuration: {msg}"
        
        # Reload nginx
        success, msg = await self.reload_nginx()
        if not success:
            return False, f"Failed to reload nginx: {msg}"
        
        return True, f"Nginx configured for {manifest.name} at {manifest.defaultPath}"
    
    async def remove_config(self, manifest: BusiboxManifest) -> Tuple[bool, str]:
        """Remove nginx configuration for app via SSH"""
        
        target = f"{self.enabled_dir}/{manifest.id}.conf"
        source = f"{self.config_dir}/{manifest.id}.conf"
        
        command = f"""
rm -f {target}
rm -f {source}
"""
        
        stdout, stderr, code = await execute_ssh_command(self.nginx_host, command)
        
        if code != 0:
            logger.error(f"Failed to remove nginx config: {stderr}")
            return False, f"Failed to remove: {stderr}"
        
        # Reload nginx
        await self.reload_nginx()
        
        logger.info(f"Nginx config removed for {manifest.id}")
        return True, f"Removed config for {manifest.id}"
