#!/usr/bin/env python3
"""
Milvus Hybrid Search Schema Initialization Script

This script creates the 'documents' collection with support for:
- Dense semantic embeddings (text-embedding-3-small, 1536 dims)
- Sparse BM25 vectors (auto-generated by Milvus)
- Multi-vector ColPali embeddings (128 patches × 128 dims per PDF page)

Usage:
    python hybrid_schema.py

Environment Variables:
    MILVUS_HOST: Milvus server host (default: localhost)
    MILVUS_PORT: Milvus server port (default: 19530)
"""

import os
import sys
from pymilvus import (
    connections,
    utility,
    FieldSchema,
    CollectionSchema,
    DataType,
    Collection,
)


def get_config():
    """Get configuration from environment variables with defaults."""
    return {
        "host": os.getenv("MILVUS_HOST", "localhost"),
        "port": int(os.getenv("MILVUS_PORT", "19530")),
        "collection_name": "documents",
    }


def connect_milvus(host, port):
    """Connect to Milvus server."""
    print(f"Connecting to Milvus at {host}:{port}...")
    try:
        connections.connect("default", host=host, port=port)
        print("✓ Connected successfully")
        return True
    except Exception as e:
        print(f"✗ Connection failed: {e}")
        return False


def create_collection(collection_name):
    """Create the documents collection with hybrid search schema."""
    
    # Check if collection already exists
    if utility.has_collection(collection_name):
        print(f"Collection '{collection_name}' already exists")
        
        # Get existing collection and verify schema
        collection = Collection(collection_name)
        print(f"  - Current entities: {collection.num_entities}")
        print(f"  - Schema: {len(collection.schema.fields)} fields")
        
        # Verify required fields exist
        field_names = [f.name for f in collection.schema.fields]
        required_fields = ["id", "file_id", "text", "text_dense", "text_sparse", "modality"]
        missing_fields = [f for f in required_fields if f not in field_names]
        
        if missing_fields:
            print(f"  ⚠ WARNING: Missing required fields: {missing_fields}")
            print("  Consider dropping and recreating the collection")
            return collection
        else:
            print("  ✓ All required fields present")
            return collection
    
    print(f"Creating collection '{collection_name}' with hybrid search schema...")
    
    # Define schema fields
    fields = [
        # Primary key and references
        FieldSchema(
            name="id",
            dtype=DataType.VARCHAR,
            is_primary=True,
            max_length=64,
            description="Unique identifier (UUID)"
        ),
        FieldSchema(
            name="file_id",
            dtype=DataType.VARCHAR,
            max_length=64,
            description="Reference to ingestion_files.file_id"
        ),
        FieldSchema(
            name="chunk_index",
            dtype=DataType.INT64,
            description="Chunk position in document (-1 for page images)"
        ),
        FieldSchema(
            name="page_number",
            dtype=DataType.INT64,
            description="PDF page number (1-indexed)"
        ),
        
        # Modality indicator
        FieldSchema(
            name="modality",
            dtype=DataType.VARCHAR,
            max_length=20,
            description="'text' for text chunks, 'page_image' for PDF pages"
        ),
        
        # Text content (for BM25 and retrieval)
        FieldSchema(
            name="text",
            dtype=DataType.VARCHAR,
            max_length=65535,
            description="Chunk text or page placeholder"
        ),
        
        # Dense semantic embeddings
        FieldSchema(
            name="text_dense",
            dtype=DataType.FLOAT_VECTOR,
            dim=1536,  # text-embedding-3-small dimension
            description="Dense text embeddings"
        ),
        
        # Sparse BM25 embeddings (auto-generated by Milvus from text field)
        FieldSchema(
            name="text_sparse",
            dtype=DataType.SPARSE_FLOAT_VECTOR,
            description="BM25 sparse embeddings (auto-generated by Milvus)"
        ),
        
        # ColPali multi-vector embeddings (PDF pages only)
        FieldSchema(
            name="page_vectors",
            dtype=DataType.FLOAT_VECTOR,
            dim=128,  # ColPali patch dimension (128 patches per page)
            description="ColPali patch embeddings (128 patches per page)"
        ),
        
        # User ownership for filtering
        FieldSchema(
            name="user_id",
            dtype=DataType.VARCHAR,
            max_length=64,
            description="User who owns this document"
        ),
        
        # Additional metadata
        FieldSchema(
            name="metadata",
            dtype=DataType.JSON,
            description="Chunk-level metadata (section, keywords, etc.)"
        ),
    ]
    
    # Create schema
    schema = CollectionSchema(
        fields=fields,
        description="Hybrid search collection with dense, sparse, and visual vectors"
    )
    
    # Create collection
    collection = Collection(
        name=collection_name,
        schema=schema,
        consistency_level="Strong"  # Ensure writes visible immediately
    )
    
    print(f"✓ Collection '{collection_name}' created")
    
    # Note: BM25 sparse vectors in Milvus 2.4+ can be auto-generated via Functions API
    # However, for better control and flexibility, we'll generate them client-side
    # in the ingestion service using a BM25 library
    print("  Note: BM25 sparse vectors will be generated client-side for better control")
    
    return collection


def create_indexes(collection):
    """Create indexes for all vector fields."""
    print("Creating indexes...")
    
    indexes_created = []
    
    # Index for dense embeddings (HNSW for high recall)
    if not collection.has_index(field_name="text_dense"):
        print("  Creating HNSW index on text_dense...")
        collection.create_index(
            field_name="text_dense",
            index_params={
                "index_type": "HNSW",
                "metric_type": "COSINE",
                "params": {"M": 16, "efConstruction": 200}
            }
        )
        indexes_created.append("text_dense")
        print("    ✓ HNSW index created (COSINE metric)")
    else:
        print("    Index on text_dense already exists")
    
    # Index for sparse embeddings (SPARSE_INVERTED_INDEX)
    if not collection.has_index(field_name="text_sparse"):
        print("  Creating SPARSE_INVERTED_INDEX on text_sparse...")
        collection.create_index(
            field_name="text_sparse",
            index_params={
                "index_type": "SPARSE_INVERTED_INDEX",
                "metric_type": "IP"  # Inner product for sparse
            }
        )
        indexes_created.append("text_sparse")
        print("    ✓ SPARSE_INVERTED_INDEX created (IP metric)")
    else:
        print("    Index on text_sparse already exists")
    
    # Index for ColPali page vectors (HNSW)
    if not collection.has_index(field_name="page_vectors"):
        print("  Creating HNSW index on page_vectors...")
        collection.create_index(
            field_name="page_vectors",
            index_params={
                "index_type": "HNSW",
                "metric_type": "L2",
                "params": {"M": 16, "efConstruction": 200}
            }
        )
        indexes_created.append("page_vectors")
        print("    ✓ HNSW index created (L2 metric)")
    else:
        print("    Index on page_vectors already exists")
    
    # Index on user_id for filtering
    if not collection.has_index(field_name="user_id"):
        print("  Creating STL_SORT index on user_id...")
        collection.create_index(
            field_name="user_id",
            index_params={"index_type": "STL_SORT"}
        )
        indexes_created.append("user_id")
        print("    ✓ STL_SORT index created")
    else:
        print("    Index on user_id already exists")
    
    if indexes_created:
        print(f"✓ Created {len(indexes_created)} indexes: {', '.join(indexes_created)}")
    else:
        print("✓ All indexes already exist")


def load_collection(collection):
    """Load collection into memory for querying."""
    print("Loading collection into memory...")
    
    # is_loaded is now a method in pymilvus 2.6+
    try:
        loaded = collection.is_loaded()
    except TypeError:
        # Fallback for older versions where is_loaded was a property
        loaded = collection.is_loaded
    
    if loaded:
        print("  Collection already loaded")
    else:
        collection.load()
        print("  ✓ Collection loaded and ready for queries")


def verify_setup(collection):
    """Verify the collection is properly set up."""
    print("\nVerification:")
    print(f"  Collection name: {collection.name}")
    print(f"  Schema fields: {len(collection.schema.fields)}")
    print(f"  Current entities: {collection.num_entities}")
    try:
        loaded = collection.is_loaded()
    except TypeError:
        loaded = collection.is_loaded
    print(f"  Loaded: {loaded}")
    
    # Display field details
    print("\n  Fields:")
    for field in collection.schema.fields:
        field_type = field.dtype.name
        extra = ""
        if field_type == "FLOAT_VECTOR":
            extra = f", dim={field.params.get('dim', 'N/A')}"
        elif field.dtype == DataType.VARCHAR:
            extra = f", max_length={field.params.get('max_length', 'N/A')}"
        print(f"    - {field.name} ({field_type}{extra})")
    
    # Display indexes
    print("\n  Indexes:")
    if collection.has_index():
        indexes = collection.indexes
        for index in indexes:
            index_type = index.params.get('index_type', 'unknown')
            metric = index.params.get('metric_type', 'N/A')
            print(f"    - {index.field_name}: {index_type} ({metric})")
    else:
        print("    (No indexes found)")


def main():
    """Main execution function."""
    print("=" * 60)
    print("Busibox Milvus Hybrid Search Schema Initialization")
    print("=" * 60)
    print()
    
    # Get configuration
    config = get_config()
    
    print(f"Configuration:")
    print(f"  Host: {config['host']}")
    print(f"  Port: {config['port']}")
    print(f"  Collection Name: {config['collection_name']}")
    print()
    
    # Connect to Milvus
    if not connect_milvus(config["host"], config["port"]):
        sys.exit(1)
    
    print()
    
    # Create collection
    collection = create_collection(config["collection_name"])
    
    print()
    
    # Create indexes
    create_indexes(collection)
    
    print()
    
    # Load collection
    load_collection(collection)
    
    # Verify setup
    verify_setup(collection)
    
    print()
    print("=" * 60)
    print("✓ Milvus hybrid search schema initialization complete!")
    print("=" * 60)
    print()
    print("Note: BM25 sparse vectors are auto-generated by Milvus")
    print("      when inserting data with the 'text' field populated.")
    print()
    
    # Disconnect
    connections.disconnect("default")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

