#!/usr/bin/env python3
"""
Milvus Hybrid Search Schema Initialization Script

This script creates the 'documents' collection with support for:
- Dense semantic embeddings (FastEmbed bge-large-en-v1.5, 1024 dims)
- Sparse BM25 vectors (auto-generated by Milvus 2.6+ Function API)
- ColPali pooled embeddings (128 dims per PDF page, mean-pooled from patches)

Milvus 2.6+ Full-Text Search:
- The 'text' field has enable_analyzer=True for automatic tokenization
- A BM25 Function auto-generates sparse vectors from text
- Search can pass raw text queries - Milvus handles BM25 conversion internally

Usage:
    python hybrid_schema.py

Environment Variables:
    MILVUS_HOST: Milvus server host (default: localhost)
    MILVUS_PORT: Milvus server port (default: 19530)
"""

import os
import sys
from pymilvus import (
    connections,
    utility,
    FieldSchema,
    CollectionSchema,
    DataType,
    Collection,
    Function,
    FunctionType,
)


def get_config():
    """Get configuration from environment variables with defaults."""
    return {
        "host": os.getenv("MILVUS_HOST", "localhost"),
        "port": int(os.getenv("MILVUS_PORT", "19530")),
        "collection_name": "documents",
        # Embedding dimension from model registry (set by Ansible)
        "embedding_dim": int(os.getenv("EMBEDDING_DIMENSION", "1024")),
    }


def connect_milvus(host, port):
    """Connect to Milvus server."""
    print(f"Connecting to Milvus at {host}:{port}...")
    try:
        connections.connect("default", host=host, port=port)
        print("✓ Connected successfully")
        return True
    except Exception as e:
        print(f"✗ Connection failed: {e}")
        return False


def create_collection(collection_name, config=None):
    """Create the documents collection with hybrid search schema.
    
    Args:
        collection_name: Name of the collection to create
        config: Configuration dict with embedding_dim (from get_config())
    """
    if config is None:
        config = get_config()
    
    embedding_dim = config.get("embedding_dim", 1024)
    print(f"Using embedding dimension: {embedding_dim}")
    
    # Check if collection already exists
    if utility.has_collection(collection_name):
        print(f"Collection '{collection_name}' already exists")
        
        # Get existing collection and verify schema
        collection = Collection(collection_name)
        print(f"  - Current entities: {collection.num_entities}")
        print(f"  - Schema: {len(collection.schema.fields)} fields")
        
        # Verify required fields exist
        field_names = [f.name for f in collection.schema.fields]
        required_fields = ["id", "file_id", "text", "text_dense", "text_sparse", "modality"]
        missing_fields = [f for f in required_fields if f not in field_names]
        
        if missing_fields:
            print(f"  ⚠ WARNING: Missing required fields: {missing_fields}")
            print("  Consider dropping and recreating the collection")
            return collection
        else:
            print("  ✓ All required fields present")
            return collection
    
    print(f"Creating collection '{collection_name}' with hybrid search schema...")
    
    # Define schema fields
    fields = [
        # Primary key and references
        FieldSchema(
            name="id",
            dtype=DataType.VARCHAR,
            is_primary=True,
            max_length=64,
            description="Unique identifier (UUID)"
        ),
        FieldSchema(
            name="file_id",
            dtype=DataType.VARCHAR,
            max_length=64,
            description="Reference to ingestion_files.file_id"
        ),
        FieldSchema(
            name="chunk_index",
            dtype=DataType.INT64,
            description="Chunk position in document (-1 for page images)"
        ),
        FieldSchema(
            name="page_number",
            dtype=DataType.INT64,
            description="PDF page number (1-indexed)"
        ),
        
        # Modality indicator
        FieldSchema(
            name="modality",
            dtype=DataType.VARCHAR,
            max_length=20,
            description="'text' for text chunks, 'page_image' for PDF pages"
        ),
        
        # Text content (for BM25 full-text search)
        # enable_analyzer=True allows Milvus to tokenize text for BM25
        FieldSchema(
            name="text",
            dtype=DataType.VARCHAR,
            max_length=65535,
            enable_analyzer=True,  # Milvus 2.6+ tokenization for BM25
            analyzer_params={"type": "english"},  # English analyzer for better tokenization
            description="Chunk text or page placeholder (analyzed for full-text search)"
        ),
        
        # Dense semantic embeddings
        # Dimension comes from EMBEDDING_DIMENSION env var (set by Ansible from model_registry)
        FieldSchema(
            name="text_dense",
            dtype=DataType.FLOAT_VECTOR,
            dim=embedding_dim,  # From model registry via env var
            description="Dense text embeddings from Marker/Simple extraction"
        ),
        
        # Sparse BM25 embeddings (auto-generated by Milvus BM25 Function)
        FieldSchema(
            name="text_sparse",
            dtype=DataType.SPARSE_FLOAT_VECTOR,
            description="BM25 sparse embeddings (auto-generated by Milvus Function)"
        ),
        
        # ColPali pooled embeddings (PDF pages only)
        FieldSchema(
            name="page_vectors",
            dtype=DataType.FLOAT_VECTOR,
            dim=128,  # ColPali pooled vector (mean-pooled from multi-patch)
            description="ColPali pooled page embeddings (128-d per page)"
        ),
        
        # User ownership for filtering
        FieldSchema(
            name="user_id",
            dtype=DataType.VARCHAR,
            max_length=64,
            description="User who owns this document"
        ),
        
        # Additional metadata
        FieldSchema(
            name="metadata",
            dtype=DataType.JSON,
            description="Chunk-level metadata (section, keywords, etc.)"
        ),
    ]
    
    # Create schema
    schema = CollectionSchema(
        fields=fields,
        description="Hybrid search collection with dense, sparse, and visual vectors"
    )
    
    # Add BM25 Function for automatic sparse vector generation (Milvus 2.6+)
    # This function automatically converts text -> sparse BM25 vectors on insert/search
    bm25_function = Function(
        name="text_bm25_emb",
        input_field_names=["text"],
        output_field_names=["text_sparse"],
        function_type=FunctionType.BM25,
    )
    schema.add_function(bm25_function)
    print("  ✓ BM25 Function added for automatic sparse vector generation")
    
    # Create collection
    collection = Collection(
        name=collection_name,
        schema=schema,
        consistency_level="Strong"  # Ensure writes visible immediately
    )
    
    print(f"✓ Collection '{collection_name}' created")
    print("  Note: BM25 sparse vectors are auto-generated by Milvus from the 'text' field")
    print("        No client-side BM25 generation needed!")
    
    return collection


def create_indexes(collection):
    """Create indexes for all vector fields."""
    print("Creating indexes...")
    
    # Get list of existing indexes
    existing_indexes = collection.indexes
    existing_index_fields = {idx.field_name for idx in existing_indexes}
    print(f"  Existing indexed fields: {existing_index_fields if existing_index_fields else 'none'}")
    
    indexes_created = []
    
    # Index for dense embeddings (HNSW for high recall)
    if "text_dense" not in existing_index_fields:
        print("  Creating HNSW index on text_dense...")
        collection.create_index(
            field_name="text_dense",
            index_params={
                "index_type": "HNSW",
                "metric_type": "COSINE",
                "params": {"M": 16, "efConstruction": 200}
            }
        )
        indexes_created.append("text_dense")
        print("    ✓ HNSW index created (COSINE metric)")
    else:
        print("    Index on text_dense already exists")
    
    # Index for sparse embeddings (SPARSE_INVERTED_INDEX with BM25 metric)
    if "text_sparse" not in existing_index_fields:
        print("  Creating SPARSE_INVERTED_INDEX on text_sparse (BM25 metric)...")
        collection.create_index(
            field_name="text_sparse",
            index_params={
                "index_type": "SPARSE_INVERTED_INDEX",
                "metric_type": "BM25"  # BM25 metric for Milvus 2.6+ full-text search
            }
        )
        indexes_created.append("text_sparse")
        print("    ✓ SPARSE_INVERTED_INDEX created (BM25 metric)")
    else:
        print("    Index on text_sparse already exists")
    
    # Index for ColPali page vectors (HNSW)
    if "page_vectors" not in existing_index_fields:
        print("  Creating HNSW index on page_vectors...")
        collection.create_index(
            field_name="page_vectors",
            index_params={
                "index_type": "HNSW",
                "metric_type": "L2",
                "params": {"M": 16, "efConstruction": 200}
            }
        )
        indexes_created.append("page_vectors")
        print("    ✓ HNSW index created (L2 metric)")
    else:
        print("    Index on page_vectors already exists")
    
    # Index on user_id for filtering
    if "user_id" not in existing_index_fields:
        print("  Creating INVERTED index on user_id...")
        collection.create_index(
            field_name="user_id",
            index_params={"index_type": "INVERTED"}
        )
        indexes_created.append("user_id")
        print("    ✓ INVERTED index created")
    else:
        print("    Index on user_id already exists")
    
    if indexes_created:
        print(f"✓ Created {len(indexes_created)} indexes: {', '.join(indexes_created)}")
    else:
        print("✓ All indexes already exist")


def load_collection(collection):
    """Load collection into memory for querying."""
    print("Loading collection into memory...")
    
    # Use utility.load_state to check if collection is loaded (pymilvus 2.6+)
    load_state = utility.load_state(collection.name)
    if load_state.name == "Loaded":
        print("  Collection already loaded")
    else:
        collection.load()
        print("  ✓ Collection loaded and ready for queries")


def verify_setup(collection):
    """Verify the collection is properly set up."""
    print("\nVerification:")
    print(f"  Collection name: {collection.name}")
    print(f"  Schema fields: {len(collection.schema.fields)}")
    print(f"  Current entities: {collection.num_entities}")
    
    # Use utility.load_state to check if collection is loaded
    load_state = utility.load_state(collection.name)
    print(f"  Loaded: {load_state.name == 'Loaded'}")
    
    # Display field details
    print("\n  Fields:")
    for field in collection.schema.fields:
        field_type = field.dtype.name
        extra = ""
        if field_type == "FLOAT_VECTOR":
            extra = f", dim={field.params.get('dim', 'N/A')}"
        elif field.dtype == DataType.VARCHAR:
            extra = f", max_length={field.params.get('max_length', 'N/A')}"
        print(f"    - {field.name} ({field_type}{extra})")
    
    # Display index details
    print("\n  Indexes:")
    if collection.indexes:
        for index in collection.indexes:
            print(f"    - Field: {index.field_name}")
            print(f"      Index type: {index.params.get('index_type', 'N/A')}")
            print(f"      Metric type: {index.params.get('metric_type', 'N/A')}")
    else:
        print("    No indexes found")

    print("\n============================================================")


def drop_collection(collection_name):
    """Drop collection if it exists."""
    if utility.has_collection(collection_name):
        print(f"Dropping existing collection '{collection_name}'...")
        try:
            utility.drop_collection(collection_name)
            print(f"✓ Collection '{collection_name}' dropped")
            return True
        except Exception as e:
            print(f"✗ Failed to drop collection: {e}")
            return False
    else:
        print(f"Collection '{collection_name}' does not exist (nothing to drop)")
        return True


def main():
    """Main execution function."""
    print("=" * 60)
    print("Busibox Milvus Hybrid Search Schema Initialization")
    print("=" * 60)
    print()
    
    # Check for --drop flag
    drop_existing = "--drop" in sys.argv
    
    # Get configuration
    config = get_config()
    
    print(f"Configuration:")
    print(f"  Host: {config['host']}")
    print(f"  Port: {config['port']}")
    print(f"  Collection Name: {config['collection_name']}")
    print(f"  Embedding Dimension: {config['embedding_dim']}")
    print(f"  Drop Existing: {drop_existing}")
    print()
    
    # Connect to Milvus
    if not connect_milvus(config["host"], config["port"]):
        sys.exit(1)
    
    print()
    
    # Drop existing collection if requested
    if drop_existing:
        if not drop_collection(config["collection_name"]):
            sys.exit(1)
        print()
    
    # Create collection (pass config for embedding_dim)
    collection = create_collection(config["collection_name"], config)
    
    print()
    
    # Create indexes
    create_indexes(collection)
    
    print()
    
    # Load collection
    load_collection(collection)
    
    # Verify setup
    verify_setup(collection)
    
    print()
    print("=" * 60)
    print("✓ Milvus hybrid search schema initialization complete!")
    print("=" * 60)
    print()
    print("Milvus 2.6+ Full-Text Search is enabled:")
    print("  - BM25 Function auto-generates sparse vectors from 'text' field")
    print("  - Insert raw text - Milvus handles tokenization and BM25 vectors")
    print("  - Search with raw text queries - no client-side embedding needed")
    print("  - Hybrid search combines dense (semantic) + sparse (BM25) results")
    print()
    
    # Disconnect
    connections.disconnect("default")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

