"""
Milvus service for hybrid vector operations.

Handles insertion of dense and multi-vector (ColPali) embeddings.
BM25 sparse vectors are auto-generated by Milvus 2.6+ via the BM25 Function.

Partition Strategy for Role-Based Access:
- personal_{user_id}: Personal documents (owner-only access)
- role_{role_id}: Shared documents by role
- Documents with multiple roles are inserted into ALL role partitions (duplicate vectors)

Auto-initialization:
- If the 'documents' collection doesn't exist, it will be created automatically
- This allows the data-worker to bootstrap itself without manual Milvus setup
"""

import uuid
from typing import Dict, List, Optional

import structlog
from pymilvus import (
    Collection,
    CollectionSchema,
    DataType,
    FieldSchema,
    Function,
    FunctionType,
    connections,
    utility,
)

logger = structlog.get_logger()


class MilvusConnectionError(Exception):
    """Raised when Milvus connection fails or times out."""
    pass


class MilvusService:
    """Service for Milvus vector database operations with role-based partitions."""
    
    # Connection timeout in seconds
    CONNECTION_TIMEOUT = 5
    
    def __init__(self, config: dict):
        """Initialize Milvus service with configuration."""
        self.config = config
        self.host = config.get("milvus_host", "milvus")
        self.port = config.get("milvus_port", "19530")
        self.collection_name = config.get("milvus_collection", "documents")
        
        # Get embedding dimension from config (set via EMBEDDING_DIMENSION env var)
        self.embedding_dimension = config.get("embedding_dimension", 1024)
        
        self.connected = False
        self.collection: Optional[Collection] = None
        
        # Cache of created partitions to avoid repeated checks
        self._partition_cache: set = set()
        
        # Track if Milvus is known to be unavailable (avoid repeated connection attempts)
        self._unavailable = False
        self._last_connect_attempt = 0
        self._retry_interval = 30  # Seconds before retrying after failure
    
    def is_available(self) -> bool:
        """Check if Milvus is likely available (without blocking)."""
        import time
        
        if self.connected:
            return True
        
        # If we recently failed, don't try again immediately
        if self._unavailable:
            if time.time() - self._last_connect_attempt < self._retry_interval:
                return False
        
        return True
    
    def _create_collection(self) -> Collection:
        """
        Create the documents collection with hybrid search schema.
        
        This mirrors the schema from hybrid_schema.py but runs automatically
        when the collection doesn't exist, allowing the data-worker to
        bootstrap itself without manual Milvus initialization.
        
        Returns:
            The created Collection object
        """
        logger.info(
            "Creating Milvus collection",
            collection_name=self.collection_name,
            embedding_dimension=self.embedding_dimension,
        )
        
        # Define schema fields (matching hybrid_schema.py)
        fields = [
            # Primary key and references
            FieldSchema(
                name="id",
                dtype=DataType.VARCHAR,
                is_primary=True,
                max_length=64,
                description="Unique identifier (UUID)"
            ),
            FieldSchema(
                name="file_id",
                dtype=DataType.VARCHAR,
                max_length=64,
                description="Reference to data_files.file_id"
            ),
            FieldSchema(
                name="chunk_index",
                dtype=DataType.INT64,
                description="Chunk position in document (-1 for page images)"
            ),
            FieldSchema(
                name="page_number",
                dtype=DataType.INT64,
                description="PDF page number (1-indexed)"
            ),
            
            # Modality indicator
            FieldSchema(
                name="modality",
                dtype=DataType.VARCHAR,
                max_length=20,
                description="'text' for text chunks, 'page_image' for PDF pages"
            ),
            
            # Text content (for BM25 full-text search)
            FieldSchema(
                name="text",
                dtype=DataType.VARCHAR,
                max_length=65535,
                enable_analyzer=True,  # Milvus 2.6+ tokenization for BM25
                analyzer_params={"type": "english"},
                description="Chunk text or page placeholder (analyzed for full-text search)"
            ),
            
            # Dense semantic embeddings
            FieldSchema(
                name="text_dense",
                dtype=DataType.FLOAT_VECTOR,
                dim=self.embedding_dimension,
                description="Dense text embeddings from embedding model"
            ),
            
            # Sparse BM25 embeddings (auto-generated by Milvus BM25 Function)
            FieldSchema(
                name="text_sparse",
                dtype=DataType.SPARSE_FLOAT_VECTOR,
                description="BM25 sparse embeddings (auto-generated by Milvus Function)"
            ),
            
            # ColPali pooled embeddings (PDF pages only)
            FieldSchema(
                name="page_vectors",
                dtype=DataType.FLOAT_VECTOR,
                dim=128,  # ColPali pooled vector (mean-pooled from multi-patch)
                description="ColPali pooled page embeddings (128-d per page)"
            ),
            
            # User ownership for filtering
            FieldSchema(
                name="user_id",
                dtype=DataType.VARCHAR,
                max_length=64,
                description="User who owns this document"
            ),
            
            # Additional metadata
            FieldSchema(
                name="metadata",
                dtype=DataType.JSON,
                description="Chunk-level metadata (section, keywords, etc.)"
            ),
        ]
        
        # Create schema
        schema = CollectionSchema(
            fields=fields,
            description="Hybrid search collection with dense, sparse, and visual vectors"
        )
        
        # Add BM25 Function for automatic sparse vector generation (Milvus 2.6+)
        bm25_function = Function(
            name="text_bm25_emb",
            input_field_names=["text"],
            output_field_names=["text_sparse"],
            function_type=FunctionType.BM25,
        )
        schema.add_function(bm25_function)
        
        # Create collection
        collection = Collection(
            name=self.collection_name,
            schema=schema,
            consistency_level="Strong"
        )
        
        logger.info("Collection created, creating indexes...")
        
        # Create indexes
        # Index for dense embeddings (HNSW for high recall)
        collection.create_index(
            field_name="text_dense",
            index_params={
                "index_type": "HNSW",
                "metric_type": "COSINE",
                "params": {"M": 16, "efConstruction": 200}
            }
        )
        logger.info("Created HNSW index on text_dense")
        
        # Index for sparse embeddings (SPARSE_INVERTED_INDEX with BM25 metric)
        collection.create_index(
            field_name="text_sparse",
            index_params={
                "index_type": "SPARSE_INVERTED_INDEX",
                "metric_type": "BM25"
            }
        )
        logger.info("Created SPARSE_INVERTED_INDEX on text_sparse")
        
        # Index for ColPali page vectors (HNSW)
        collection.create_index(
            field_name="page_vectors",
            index_params={
                "index_type": "HNSW",
                "metric_type": "L2",
                "params": {"M": 16, "efConstruction": 200}
            }
        )
        logger.info("Created HNSW index on page_vectors")
        
        # Index on user_id for filtering
        collection.create_index(
            field_name="user_id",
            index_params={"index_type": "INVERTED"}
        )
        logger.info("Created INVERTED index on user_id")
        
        logger.info(
            "Milvus collection created successfully",
            collection_name=self.collection_name,
            embedding_dimension=self.embedding_dimension,
        )
        
        return collection
    
    def connect(self, timeout: Optional[float] = None):
        """
        Connect to Milvus and load collection.
        
        If the collection doesn't exist, it will be created automatically.
        This allows the data-worker to bootstrap itself without manual
        Milvus initialization via hybrid_schema.py.
        
        Args:
            timeout: Connection timeout in seconds (default: CONNECTION_TIMEOUT)
        
        Raises:
            MilvusConnectionError: If connection fails or times out
        """
        import time
        
        if self.connected:
            return
        
        # Check if we should skip due to recent failure
        if self._unavailable:
            if time.time() - self._last_connect_attempt < self._retry_interval:
                raise MilvusConnectionError(
                    f"Milvus unavailable (last attempt {int(time.time() - self._last_connect_attempt)}s ago, retry in {self._retry_interval}s)"
                )
        
        self._last_connect_attempt = time.time()
        connect_timeout = timeout or self.CONNECTION_TIMEOUT
        
        try:
            connections.connect(
                "default",
                host=self.host,
                port=self.port,
                timeout=connect_timeout,
            )
            
            # Check if collection exists, create if not
            if not utility.has_collection(self.collection_name):
                logger.warning(
                    "Collection does not exist, creating it automatically",
                    collection_name=self.collection_name,
                    embedding_dimension=self.embedding_dimension,
                )
                self.collection = self._create_collection()
            else:
                self.collection = Collection(self.collection_name)
            
            # Load collection into memory for querying
            load_state = utility.load_state(self.collection_name)
            if load_state.name != "Loaded":
                self.collection.load()
            
            self.connected = True
            self._unavailable = False
            
            logger.info(
                "Connected to Milvus",
                host=self.host,
                port=self.port,
                collection=self.collection_name,
                entities=self.collection.num_entities,
            )
        
        except Exception as e:
            self._unavailable = True
            logger.error(
                "Failed to connect to Milvus",
                host=self.host,
                port=self.port,
                error=str(e),
                timeout=connect_timeout,
            )
            raise MilvusConnectionError(f"Failed to connect to Milvus: {e}")
    
    def close(self):
        """Close Milvus connections."""
        if self.connected:
            try:
                connections.disconnect("default")
                self.connected = False
                self._partition_cache.clear()
                logger.info("Disconnected from Milvus")
            except Exception as e:
                logger.warning("Error disconnecting from Milvus", error=str(e))
    
    # ========================================================================
    # Partition Management
    # ========================================================================
    
    def get_partition_name(self, visibility: str, user_id: str, role_id: Optional[str] = None) -> str:
        """
        Get partition name based on document visibility.
        
        Personal docs: personal_{user_id}
        Shared docs: role_{role_id}
        """
        if visibility == "personal":
            return f"personal_{user_id}"
        elif visibility == "shared" and role_id:
            return f"role_{role_id}"
        else:
            raise ValueError(f"Invalid visibility '{visibility}' or missing role_id for shared doc")
    
    def get_partition_names_for_document(
        self,
        visibility: str,
        user_id: str,
        role_ids: Optional[List[str]] = None
    ) -> List[str]:
        """
        Get all partition names for a document.
        
        For personal docs: [personal_{user_id}]
        For shared docs: [role_{role_id} for each role_id]
        """
        if visibility == "personal":
            return [f"personal_{user_id}"]
        elif visibility == "shared":
            if not role_ids:
                raise ValueError("Shared documents must have at least one role_id")
            return [f"role_{role_id}" for role_id in role_ids]
        else:
            raise ValueError(f"Invalid visibility: {visibility}")
    
    def ensure_partition_exists(self, partition_name: str):
        """Create partition if it doesn't exist."""
        if not self.connected:
            self.connect()
        
        # Check cache first
        if partition_name in self._partition_cache:
            return
        
        try:
            if not self.collection.has_partition(partition_name):
                self.collection.create_partition(partition_name)
                logger.info("Created Milvus partition", partition_name=partition_name)
            
            self._partition_cache.add(partition_name)
        except Exception as e:
            logger.error(
                "Failed to create partition",
                partition_name=partition_name,
                error=str(e),
            )
            raise
    
    def ensure_partitions_exist(self, partition_names: List[str]):
        """Create multiple partitions if they don't exist."""
        for partition_name in partition_names:
            self.ensure_partition_exists(partition_name)
    
    def list_partitions(self) -> List[str]:
        """List all partitions in the collection. Returns empty list if Milvus unavailable."""
        try:
            if not self.connected:
                self.connect()
        except MilvusConnectionError:
            return []
        
        try:
            return [p.name for p in self.collection.partitions]
        except Exception as e:
            logger.warning("Failed to list partitions", error=str(e))
            return []
    
    def insert_text_chunks(
        self,
        file_id: str,
        user_id: str,
        chunks: List[Dict],
        embeddings: List[List[float]],
        content_hash: str,
        visibility: str = "personal",
        role_ids: Optional[List[str]] = None,
    ) -> int:
        """
        Insert text chunks with dense embeddings into appropriate partitions.
        
        BM25 sparse vectors (text_sparse) are auto-generated by Milvus 2.6+
        via the BM25 Function defined in the collection schema.
        
        For role-based access control:
        - Personal docs: Inserted into personal_{user_id} partition
        - Shared docs: Inserted into ALL role_{role_id} partitions (duplicate vectors)
        
        Args:
            file_id: File identifier
            user_id: User identifier
            chunks: List of chunk dictionaries with text, chunk_index, page_number, etc.
            embeddings: List of dense embedding vectors (1024-d from FastEmbed bge-large-en-v1.5)
            content_hash: Content hash for vector reuse
            visibility: 'personal' or 'shared'
            role_ids: List of role IDs (required if visibility='shared')
        
        Returns:
            Number of vectors inserted (total across all partitions)
        """
        if not self.connected:
            self.connect()
        
        if len(chunks) != len(embeddings):
            raise ValueError(f"Chunk count ({len(chunks)}) != embedding count ({len(embeddings)})")
        
        if len(chunks) == 0:
            logger.warning(
                "No chunks to insert into Milvus, skipping",
                file_id=file_id,
            )
            return 0
        
        # Prepare data for insertion
        # Note: text_sparse is NOT included - Milvus auto-generates it from 'text' via BM25 Function
        entities = []
        
        for i, (chunk, embedding) in enumerate(zip(chunks, embeddings)):
            vector_id = f"{file_id}-chunk-{chunk['chunk_index']}"
            
            # Validate embedding dimension matches configured dimension
            if len(embedding) != self.embedding_dimension:
                logger.error(
                    "Unexpected embedding dimension",
                    chunk_index=chunk.get("chunk_index", i),
                    expected=self.embedding_dimension,
                    actual=len(embedding),
                )
                raise ValueError(f"Expected {self.embedding_dimension}-d embeddings, got {len(embedding)}-d")
            
            entity = {
                "id": vector_id,
                "file_id": file_id,
                "chunk_index": chunk.get("chunk_index", i),
                "page_number": chunk.get("page_number") or 0,  # 0 for non-PDF chunks (None -> 0)
                "modality": "text",
                "text": chunk["text"],  # BM25 sparse vector auto-generated from this by Milvus
                "text_dense": list(embedding),  # 1024-d from FastEmbed
                # text_sparse: auto-generated by Milvus BM25 Function
                "page_vectors": [0.0] * 128,  # Empty ColPali vector (128 dims)
                "user_id": user_id,
                "metadata": {
                    "content_hash": content_hash,
                    "char_offset": chunk.get("char_offset"),
                    "section_heading": chunk.get("section_heading"),
                    "language": chunk.get("language"),
                },
            }
            
            entities.append(entity)
        
        # Determine partitions for this document
        partition_names = self.get_partition_names_for_document(visibility, user_id, role_ids)
        self.ensure_partitions_exist(partition_names)
        
        # Batch insert into all partitions
        try:
            total_inserted = 0
            
            for partition_name in partition_names:
                logger.info(
                    "Inserting text chunks into Milvus partition",
                    file_id=file_id,
                    partition=partition_name,
                    chunk_count=len(entities),
                )
                
                self.collection.insert(entities, partition_name=partition_name)
                total_inserted += len(entities)
            
            self.collection.flush()
            
            logger.info(
                "Text chunks inserted successfully",
                file_id=file_id,
                vector_count=len(entities),
                partitions=partition_names,
                total_inserted=total_inserted,
            )
            
            return total_inserted
        
        except Exception as e:
            logger.error(
                "Failed to insert text chunks",
                file_id=file_id,
                partitions=partition_names,
                error=str(e),
                exc_info=True,
            )
            raise
    
    def insert_page_images(
        self,
        file_id: str,
        user_id: str,
        page_images: List[Dict],
        page_embeddings: List[List[float]],
        content_hash: str,
        visibility: str = "personal",
        role_ids: Optional[List[str]] = None,
    ) -> int:
        """
        Insert PDF page images with ColPali pooled embeddings into appropriate partitions.
        
        For role-based access control:
        - Personal docs: Inserted into personal_{user_id} partition
        - Shared docs: Inserted into ALL role_{role_id} partitions (duplicate vectors)
        
        Args:
            file_id: File identifier
            user_id: User identifier
            page_images: List of page image metadata (page_number, image_path)
            page_embeddings: List of page embeddings (each page is a single 128-d pooled vector)
            content_hash: Content hash for vector reuse
            visibility: 'personal' or 'shared'
            role_ids: List of role IDs (required if visibility='shared')
        
        Returns:
            Number of vectors inserted (total across all partitions)
        """
        if not self.connected:
            self.connect()
        
        if not page_embeddings:
            logger.debug("No page embeddings to insert", file_id=file_id)
            return 0
        
        if len(page_images) != len(page_embeddings):
            raise ValueError(f"Page count ({len(page_images)}) != embedding count ({len(page_embeddings)})")
        
        # Prepare data for insertion
        entities = []
        
        for page_info, page_embedding in zip(page_images, page_embeddings):
            page_number = page_info.get("page_number", 1)
            vector_id = f"{file_id}-page-{page_number}"
            
            # ColPali returns single pooled 128-d vector per page (mean-pooled from patches)
            # No need for multi-patch handling anymore
            target_dim = 128  # Match Milvus schema dimension
            
            if len(page_embedding) != target_dim:
                logger.error(
                    "Unexpected ColPali embedding dimension",
                    page_number=page_number,
                    expected=target_dim,
                    actual=len(page_embedding),
                )
                raise ValueError(f"Expected 128-d ColPali embeddings, got {len(page_embedding)}-d")
            
            # Generate zero/empty embeddings for text fields (required by Milvus schema)
            # Page images don't have text embeddings, so use zeros/empty
            zero_dense_embedding = [0.0] * self.embedding_dimension  # Match configured embedding dimension
            
            entity = {
                "id": vector_id,
                "file_id": file_id,
                "chunk_index": -1,  # Not a text chunk
                "page_number": page_number,
                "modality": "page_image",
                "text": f"Page {page_number}",  # Placeholder text (BM25 auto-generated but not useful for images)
                "text_dense": zero_dense_embedding,  # Zero vector - page images don't have text embeddings
                # text_sparse: auto-generated by Milvus BM25 Function (minimal for placeholder text)
                "page_vectors": list(page_embedding),  # Pooled ColPali vector (128 dims)
                "user_id": user_id,
                "metadata": {
                    "content_hash": content_hash,
                    "image_path": page_info.get("image_path"),
                },
            }
            
            entities.append(entity)
        
        # Determine partitions for this document
        partition_names = self.get_partition_names_for_document(visibility, user_id, role_ids)
        self.ensure_partitions_exist(partition_names)
        
        # Batch insert into all partitions
        try:
            total_inserted = 0
            
            for partition_name in partition_names:
                logger.info(
                    "Inserting page images into Milvus partition",
                    file_id=file_id,
                    partition=partition_name,
                    page_count=len(entities),
                )
                
                self.collection.insert(entities, partition_name=partition_name)
                total_inserted += len(entities)
            
            self.collection.flush()
            
            logger.info(
                "Page images inserted successfully",
                file_id=file_id,
                vector_count=len(entities),
                partitions=partition_names,
                total_inserted=total_inserted,
            )
            
            return total_inserted
        
        except Exception as e:
            logger.error(
                "Failed to insert page images",
                file_id=file_id,
                partitions=partition_names,
                error=str(e),
                exc_info=True,
            )
            raise
    
    def hybrid_search(
        self,
        query_embedding: List[float],
        user_id: str,
        top_k: int = 10,
        rerank_k: int = 100,
        dense_weight: float = 0.7,
        sparse_weight: float = 0.3,
        partition_names: Optional[List[str]] = None,
        readable_role_ids: Optional[List[str]] = None,
    ) -> List[Dict]:
        """
        Perform semantic search using dense vectors with partition filtering.
        
        Note: For full hybrid search (dense + BM25), use the search-api service
        which combines dense and sparse search with proper RRF fusion.
        This method provides basic dense semantic search for the data service.
        
        Args:
            query_embedding: Dense embedding vector for the query (1024 dims from FastEmbed)
            user_id: User ID for permission filtering
            top_k: Number of final results to return
            rerank_k: Number of candidates to retrieve before reranking
            dense_weight: Weight for dense semantic search (unused, kept for API compatibility)
            sparse_weight: Weight for sparse BM25 search (unused, kept for API compatibility)
            partition_names: Specific partitions to search (if None, builds from user_id and readable_role_ids)
            readable_role_ids: Role IDs user can read (used to build partition list)
        
        Returns:
            List of search results with file_id, chunk_index, text, score, metadata
            Returns empty list if Milvus is unavailable.
        """
        try:
            if not self.connected:
                self.connect()
        except MilvusConnectionError as e:
            logger.warning(
                "Milvus unavailable for search, returning empty results",
                user_id=user_id,
                error=str(e),
            )
            return []
        
        # Build partition list if not provided
        if partition_names is None:
            partition_names = [f"personal_{user_id}"]
            if readable_role_ids:
                partition_names.extend([f"role_{role_id}" for role_id in readable_role_ids])
        
        # Filter to only existing partitions
        existing_partitions = set(self.list_partitions())
        partition_names = [p for p in partition_names if p in existing_partitions]
        
        if not partition_names:
            logger.info("No accessible partitions found, returning empty results")
            return []
        
        try:
            logger.info(
                "Performing semantic search",
                user_id=user_id,
                partitions=partition_names,
                top_k=top_k,
                rerank_k=rerank_k,
            )
            
            # Perform dense vector search
            search_params = {
                "metric_type": "COSINE",
                "params": {"nprobe": 10},
            }
            
            # Search in specified partitions with modality filter
            results = self.collection.search(
                data=[query_embedding],
                anns_field="text_dense",
                param=search_params,
                limit=rerank_k,
                partition_names=partition_names,
                expr='modality == "text"',
                output_fields=[
                    "file_id",
                    "chunk_index",
                    "page_number",
                    "text",
                    "metadata",
                ],
            )
            
            # Process results
            search_results = []
            for hits in results:
                for hit in hits:
                    # Access entity fields using get() without default value
                    result = {
                        "file_id": hit.entity.get("file_id"),
                        "chunk_index": hit.entity.get("chunk_index"),
                        "page_number": hit.entity.get("page_number"),
                        "text": hit.entity.get("text"),
                        "score": float(hit.score),
                        "metadata": hit.entity.get("metadata") or {},
                    }
                    search_results.append(result)
            
            # Sort by score and take top_k
            search_results.sort(key=lambda x: x["score"], reverse=True)
            search_results = search_results[:top_k]
            
            logger.info(
                "Semantic search completed",
                user_id=user_id,
                result_count=len(search_results),
            )
            
            return search_results
        
        except Exception as e:
            logger.error(
                "Semantic search failed",
                user_id=user_id,
                error=str(e),
                exc_info=True,
            )
            raise
    
    def delete_file_vectors(self, file_id: str, partition_names: Optional[List[str]] = None, raise_on_unavailable: bool = False):
        """
        Delete all vectors for a file from specified partitions.
        
        If partition_names is None, deletes from all partitions (slower but complete).
        
        Args:
            file_id: File ID to delete vectors for
            partition_names: Specific partitions to delete from (None = all)
            raise_on_unavailable: If True, raise exception when Milvus unavailable.
                                  If False (default), log warning and return gracefully.
        """
        try:
            if not self.connected:
                self.connect()
        except MilvusConnectionError as e:
            if raise_on_unavailable:
                raise
            logger.warning(
                "Milvus unavailable, skipping vector deletion",
                file_id=file_id,
                error=str(e),
            )
            return
        
        try:
            expr = f'file_id == "{file_id}"'
            
            if partition_names:
                # Delete from specific partitions
                for partition_name in partition_names:
                    if partition_name in set(self.list_partitions()):
                        self.collection.delete(expr, partition_name=partition_name)
                        logger.debug("Deleted from partition", partition=partition_name)
            else:
                # Delete from all partitions
                self.collection.delete(expr)
            
            self.collection.flush()
            
            logger.info(
                "Deleted vectors for file",
                file_id=file_id,
                partitions=partition_names or "all",
            )
        
        except Exception as e:
            logger.error(
                "Failed to delete vectors",
                file_id=file_id,
                error=str(e),
                exc_info=True,
            )
            if raise_on_unavailable:
                raise
    
    def copy_vectors_to_partition(
        self,
        file_id: str,
        source_partition: str,
        target_partition: str,
    ) -> int:
        """
        Copy vectors from one partition to another.
        
        Used when adding roles to a document - need to copy vectors to new role partition.
        
        Returns number of vectors copied.
        """
        if not self.connected:
            self.connect()
        
        try:
            # Query vectors from source partition
            results = self.collection.query(
                expr=f'file_id == "{file_id}"',
                partition_names=[source_partition],
                output_fields=["*"],
            )
            
            if not results:
                logger.warning(
                    "No vectors found to copy",
                    file_id=file_id,
                    source_partition=source_partition,
                )
                return 0
            
            # Ensure target partition exists
            self.ensure_partition_exists(target_partition)
            
            # Insert into target partition
            self.collection.insert(results, partition_name=target_partition)
            self.collection.flush()
            
            logger.info(
                "Copied vectors to partition",
                file_id=file_id,
                source_partition=source_partition,
                target_partition=target_partition,
                count=len(results),
            )
            
            return len(results)
        
        except Exception as e:
            logger.error(
                "Failed to copy vectors",
                file_id=file_id,
                source_partition=source_partition,
                target_partition=target_partition,
                error=str(e),
                exc_info=True,
            )
            raise
    
    def insert_extracted_fields(
        self,
        file_id: str,
        user_id: str,
        field_entries: List[Dict],
        visibility: str = "personal",
        role_ids: Optional[List[str]] = None,
    ) -> int:
        """
        Insert extracted field values into Milvus with modality='extracted_field'.

        Each entry must include:
          - id: unique vector id (e.g. "{file_id}-field-{field_name}-{record_index}")
          - text: stringified field value
          - text_dense: embedding vector (or zeros for keyword-only)
          - metadata: {"field_name": ..., "schema_document_id": ..., "record_index": N}
        """
        if not self.connected:
            self.connect()

        if not field_entries:
            return 0

        entities = []
        for entry in field_entries:
            entities.append({
                "id": entry["id"],
                "file_id": file_id,
                "chunk_index": -2,
                "page_number": 0,
                "modality": "extracted_field",
                "text": entry["text"],
                "text_dense": entry["text_dense"],
                "page_vectors": [0.0] * 128,
                "user_id": user_id,
                "metadata": entry.get("metadata", {}),
            })

        partition_names = self.get_partition_names_for_document(visibility, user_id, role_ids)
        self.ensure_partitions_exist(partition_names)

        try:
            total_inserted = 0
            for partition_name in partition_names:
                self.collection.insert(entities, partition_name=partition_name)
                total_inserted += len(entities)

            self.collection.flush()

            logger.info(
                "Extracted fields inserted into Milvus",
                file_id=file_id,
                field_count=len(entities),
                partitions=partition_names,
                total_inserted=total_inserted,
            )
            return total_inserted

        except Exception as e:
            logger.error(
                "Failed to insert extracted fields",
                file_id=file_id,
                error=str(e),
                exc_info=True,
            )
            raise

    def delete_extracted_fields(self, file_id: str, partition_names: Optional[List[str]] = None):
        """
        Delete all extracted-field entries for a file (modality == 'extracted_field').

        Used before re-extraction to avoid stale field values.
        """
        try:
            if not self.connected:
                self.connect()
        except MilvusConnectionError as e:
            logger.warning(
                "Milvus unavailable, skipping extracted field deletion",
                file_id=file_id,
                error=str(e),
            )
            return

        try:
            expr = f'file_id == "{file_id}" and modality == "extracted_field"'

            if partition_names:
                existing = set(self.list_partitions())
                for pname in partition_names:
                    if pname in existing:
                        self.collection.delete(expr, partition_name=pname)
            else:
                self.collection.delete(expr)

            self.collection.flush()
            logger.info("Deleted extracted field vectors", file_id=file_id)

        except Exception as e:
            logger.error(
                "Failed to delete extracted field vectors",
                file_id=file_id,
                error=str(e),
                exc_info=True,
            )

    def delete_vectors_from_partition(
        self,
        file_id: str,
        partition_name: str,
    ):
        """
        Delete vectors from a specific partition.
        
        Used when removing roles from a document.
        """
        if not self.connected:
            self.connect()
        
        try:
            if partition_name not in set(self.list_partitions()):
                logger.warning(
                    "Partition doesn't exist, skipping delete",
                    partition=partition_name,
                )
                return
            
            expr = f'file_id == "{file_id}"'
            self.collection.delete(expr, partition_name=partition_name)
            self.collection.flush()
            
            logger.info(
                "Deleted vectors from partition",
                file_id=file_id,
                partition=partition_name,
            )
        
        except Exception as e:
            logger.error(
                "Failed to delete vectors from partition",
                file_id=file_id,
                partition_name=partition_name,
                error=str(e),
                exc_info=True,
            )
            raise
