#!/usr/bin/env bash
#
# Generate .env.local from Ansible Vault
#
# EXECUTION CONTEXT: Admin workstation
# PURPOSE: Generate .env.local file for Docker Compose from Ansible vault
#
# This script:
# 1. Decrypts the Ansible vault
# 2. Extracts relevant secrets for local Docker development
# 3. Generates a .env.local file with proper format
# 4. Uses inventory variables for local development defaults
#
# USAGE:
#   bash scripts/vault/generate-env-from-vault.sh
#   OR
#   make docker-generate-env
#
set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Source libraries
source "${REPO_ROOT}/scripts/lib/ui.sh"

# ============================================================================
# Configuration
# ============================================================================

ANSIBLE_DIR="${REPO_ROOT}/provision/ansible"
VAULT_FILE="${ANSIBLE_DIR}/roles/secrets/vars/vault.yml"
ENV_LOCAL="${REPO_ROOT}/.env.local"
TEMP_DIR=$(mktemp -d)

cleanup() {
    rm -rf "$TEMP_DIR"
}
trap cleanup EXIT

# ============================================================================
# Functions
# ============================================================================

get_vault_pass_args() {
    local vault_pass_file="$HOME/.vault_pass"
    if [ -f "$vault_pass_file" ]; then
        echo "--vault-password-file $vault_pass_file"
    else
        echo "--ask-vault-pass"
    fi
}

# Decrypt vault
decrypt_vault() {
    if [[ ! -f "$VAULT_FILE" ]]; then
        error "Vault file not found: $VAULT_FILE"
        error "Run: bash scripts/vault/migrate-env-to-vault.sh"
        return 1
    fi
    
    local vault_pass_args=$(get_vault_pass_args)
    
    info "Decrypting vault..."
    cd "$ANSIBLE_DIR"
    
    if ! ansible-vault view "$VAULT_FILE" $vault_pass_args > "$TEMP_DIR/vault.yml" 2>/dev/null; then
        error "Failed to decrypt vault (check password)"
        cd "$REPO_ROOT"
        return 1
    fi
    
    cd "$REPO_ROOT"
    success "Vault decrypted"
    return 0
}

# Generate .env.local file using Python
generate_env_file() {
    info "Generating .env.local from vault..."
    
    python3 -c "
import yaml
import sys
from datetime import datetime

try:
    # Load vault
    with open('$TEMP_DIR/vault.yml', 'r') as f:
        vault = yaml.safe_load(f)
    
    if not vault or 'secrets' not in vault:
        print('Error: Invalid vault structure', file=sys.stderr)
        sys.exit(1)
    
    secrets = vault['secrets']
    
    # Build .env.local content
    lines = []
    lines.append('# =============================================================================')
    lines.append('# Busibox Local Development Environment Configuration')
    lines.append('# =============================================================================')
    lines.append('#')
    lines.append('# AUTO-GENERATED from Ansible vault')
    lines.append(f'# Generated: {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}')
    lines.append('#')
    lines.append('# DO NOT EDIT THIS FILE MANUALLY!')
    lines.append('# Edit the vault instead: ansible-vault edit provision/ansible/roles/secrets/vars/vault.yml')
    lines.append('# Then regenerate: bash scripts/vault/generate-env-from-vault.sh')
    lines.append('#')
    lines.append('# =============================================================================')
    lines.append('')
    
    # DATABASE
    lines.append('# =============================================================================')
    lines.append('# DATABASE')
    lines.append('# =============================================================================')
    lines.append('')
    lines.append('POSTGRES_USER=busibox_user')
    if 'postgresql' in secrets and 'password' in secrets['postgresql']:
        lines.append(f'POSTGRES_PASSWORD={secrets[\"postgresql\"][\"password\"]}')
    else:
        lines.append('POSTGRES_PASSWORD=devpassword')
    lines.append('')
    
    # OBJECT STORAGE
    lines.append('# =============================================================================')
    lines.append('# OBJECT STORAGE (MinIO)')
    lines.append('# =============================================================================')
    lines.append('')
    if 'minio' in secrets:
        lines.append(f'MINIO_ACCESS_KEY={secrets[\"minio\"].get(\"root_user\", \"minioadmin\")}')
        lines.append(f'MINIO_SECRET_KEY={secrets[\"minio\"].get(\"root_password\", \"minioadmin\")}')
    else:
        lines.append('MINIO_ACCESS_KEY=minioadmin')
        lines.append('MINIO_SECRET_KEY=minioadmin')
    lines.append('')
    
    # LLM CONFIGURATION
    lines.append('# =============================================================================')
    lines.append('# LLM CONFIGURATION')
    lines.append('# =============================================================================')
    lines.append('')
    litellm_key = secrets.get('litellm_api_key', 'sk-local-dev-key')
    lines.append(f'LITELLM_MASTER_KEY={litellm_key}')
    lines.append('')
    
    if 'openai' in secrets and 'api_key' in secrets['openai']:
        lines.append(f'OPENAI_API_KEY={secrets[\"openai\"][\"api_key\"]}')
    else:
        lines.append('# OPENAI_API_KEY=your-key-here')
    lines.append('')
    
    if 'bedrock' in secrets and 'api_key' in secrets['bedrock']:
        lines.append(f'BEDROCK_API_KEY={secrets[\"bedrock\"][\"api_key\"]}')
        # Parse AWS credentials from BEDROCK_API_KEY if format is access_key:secret
        bedrock_key = secrets['bedrock']['api_key']
        if bedrock_key.startswith('ABSKY'):
            # Decode bedrock format
            import base64
            try:
                decoded = base64.b64decode(bedrock_key[5:]).decode('utf-8')
                if ':' in decoded:
                    access_key, secret_key = decoded.split(':', 1)
                    lines.append(f'AWS_ACCESS_KEY_ID={access_key}')
                    lines.append(f'AWS_SECRET_ACCESS_KEY={secret_key}')
                    lines.append(f'AWS_REGION_NAME={secrets[\"bedrock\"].get(\"region\", \"us-east-1\")}')
            except:
                pass
    else:
        lines.append('# BEDROCK_API_KEY=your-key-here')
    lines.append('')
    
    lines.append(f'LITELLM_API_KEY={litellm_key}')
    lines.append('LITELLM_BASE_URL=http://localhost:4000/v1')
    lines.append('')
    
    # AUTHZ CONFIGURATION
    lines.append('# =============================================================================')
    lines.append('# AUTHZ CONFIGURATION')
    lines.append('# =============================================================================')
    lines.append('')
    if 'authz' in secrets:
        lines.append(f'AUTHZ_MASTER_KEY={secrets[\"authz\"].get(\"master_key\", \"local-master-key-change-in-production\")}')
    else:
        lines.append('AUTHZ_MASTER_KEY=local-master-key-change-in-production')
    lines.append('AUTHZ_ACCESS_TOKEN_TTL=900')
    lines.append('')
    
    # Busibox Portal CONFIGURATION
    lines.append('# =============================================================================')
    lines.append('# Busibox Portal CONFIGURATION')
    lines.append('# =============================================================================')
    lines.append('')
    lines.append(f'SSO_JWT_SECRET={secrets.get(\"jwt_secret\", \"dev-sso-secret\")}')
    lines.append(f'ADMIN_EMAIL={secrets.get(\"admin_email\", \"admin@localhost\")}')
    lines.append(f'ALLOWED_EMAIL_DOMAINS={secrets.get(\"allowed_email_domains\", \"*\")}')
    lines.append('')
    
    # Email (optional)
    if 'resend_api_key' in secrets and secrets['resend_api_key'] != 'CHANGE_ME_RESEND_API_KEY':
        lines.append(f'RESEND_API_KEY={secrets[\"resend_api_key\"]}')
    else:
        lines.append('RESEND_API_KEY=')
    lines.append('EMAIL_FROM=noreply@localhost')
    lines.append('')
    
    # SMTP CONFIGURATION (for agent task notifications)
    lines.append('# =============================================================================')
    lines.append('# SMTP CONFIGURATION (for agent task notifications)')
    lines.append('# =============================================================================')
    lines.append('')
    if 'smtp' in secrets:
        smtp = secrets['smtp']
        smtp_host = smtp.get('host', '')
        smtp_port = smtp.get('port', '587')
        smtp_user = smtp.get('user', '')
        smtp_password = smtp.get('password', '')
        smtp_from = smtp.get('from_email', 'noreply@localhost')
        
        if smtp_host and smtp_host != 'CHANGE_ME_SMTP_HOST':
            lines.append(f'SMTP_HOST={smtp_host}')
            lines.append(f'SMTP_PORT={smtp_port}')
            lines.append(f'SMTP_USERNAME={smtp_user}')
            lines.append(f'SMTP_PASSWORD={smtp_password}')
            lines.append(f'SMTP_FROM={smtp_from}')
        else:
            lines.append('# SMTP_HOST=')
            lines.append('# SMTP_PORT=587')
            lines.append('# SMTP_USERNAME=')
            lines.append('# SMTP_PASSWORD=')
            lines.append('# SMTP_FROM=noreply@localhost')
    else:
        lines.append('# SMTP_HOST=')
        lines.append('# SMTP_PORT=587')
        lines.append('# SMTP_USERNAME=')
        lines.append('# SMTP_PASSWORD=')
        lines.append('# SMTP_FROM=noreply@localhost')
    lines.append('')
    
    # Portal URL for notification links
    lines.append('PORTAL_BASE_URL=https://localhost')
    lines.append('')
        
    # PROCESSING OPTIONS
    lines.append('# =============================================================================')
    lines.append('# PROCESSING OPTIONS')
    lines.append('# =============================================================================')
    lines.append('')
    lines.append('MARKER_ENABLED=true')
    lines.append('MARKER_USE_GPU=false')
    lines.append('COLPALI_ENABLED=false')
    lines.append('LLM_CLEANUP_ENABLED=true')
    lines.append('RERANKING_MODE=none')
    lines.append('')
    
    # OPTIONAL: GITHUB
    lines.append('# =============================================================================')
    lines.append('# OPTIONAL: GITHUB OAUTH (for deployment management)')
    lines.append('# =============================================================================')
    if 'github' in secrets and 'personal_access_token' in secrets['github'] and secrets['github']['personal_access_token'] != 'CHANGE_ME_GITHUB_PERSONAL_ACCESS_TOKEN':
        lines.append(f'GITHUB_AUTH_TOKEN={secrets[\"github\"].get(\"personal_access_token\", \"CHANGE_ME_GITHUB_PERSONAL_ACCESS_TOKEN\")}')
    else:
        lines.append('# GITHUB_AUTH_TOKEN=CHANGE_ME_GITHUB_PERSONAL_ACCESS_TOKEN')
    lines.append('')
    
    # Write to file
    with open('$ENV_LOCAL', 'w') as f:
        f.write('\\n'.join(lines))
    
    print('SUCCESS')
    sys.exit(0)
    
except Exception as e:
    print(f'Error: {e}', file=sys.stderr)
    import traceback
    traceback.print_exc()
    sys.exit(1)
"
    
    if [[ $? -eq 0 ]]; then
        success ".env.local generated from vault"
        return 0
    else
        error "Failed to generate .env.local"
        return 1
    fi
}

# ============================================================================
# Main
# ============================================================================

main() {
    header "Generate .env.local from Ansible Vault" 70
    
    echo ""
    info "This will:"
    echo "  1. Decrypt your Ansible vault"
    echo "  2. Extract secrets for local Docker development"
    echo "  3. Generate .env.local file"
    echo ""
    
    if [[ -f "$ENV_LOCAL" ]]; then
        warn ".env.local already exists and will be overwritten"
        echo ""
        if ! confirm "Continue?"; then
            info "Cancelled"
            return 0
        fi
    fi
    
    echo ""
    separator 70
    
    # Decrypt vault
    if ! decrypt_vault; then
        return 1
    fi
    
    # Generate .env.local
    if ! generate_env_file; then
        return 1
    fi
    
    echo ""
    separator 70
    success ".env.local generated successfully!"
    separator 70
    
    echo ""
    info "File created: ${CYAN}.env.local${NC}"
    echo ""
    info "Next steps:"
    echo ""
    echo "  1. Review the generated file:"
    echo -e "     ${CYAN}cat .env.local${NC}"
    echo ""
    echo "  2. Start Docker services:"
    echo -e "     ${CYAN}make docker-up${NC}"
    echo ""
    echo -e "  ${DIM}Note: This file is auto-generated. Edit the vault instead:${NC}"
    echo -e "  ${DIM}ansible-vault edit provision/ansible/roles/secrets/vars/vault.yml${NC}"
    echo ""
}

main "$@"
